### ISSUE TITLE
Schema of "Create table t SELECT * FROM tbl" drops default values when compared to MySql

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#6016] opened 2023-05-04 20:07 UTC
Example repro:

```sql
CREATE TABLE source (
    v1 INT PRIMARY KEY AUTO_INCREMENT,
    v2 INT DEFAULT 1,
    v3 INT 
);
CREATE TABLE dest SELECT * FROM source;
SHOW CREATE TABLE dest;
```

MySql output:

```
Table | Create Table
dest | CREATE TABLE `dest` (   `v1` int(11) NOT NULL DEFAULT '0',   `v2` int(11) DEFAULT '1',   `v3` int(11) DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
Dolt output:

```
+-------+------------------------------------------------------------------+
| Table | Create Table                                                     |
+-------+------------------------------------------------------------------+
| dest  | CREATE TABLE `dest` (                                            |
|       |   `v1` int NOT NULL,                                             |
|       |   `v2` int,                                                      |
|       |   `v3` int                                                       |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+-------+------------------------------------------------------------------+
```

**Comment by timsehn** [comment] 2023-05-24 00:23
A dupe of #6016

**Closed** 2024-04-18 21:07 UTC
Labels: bug, sql, correctness
