### ISSUE TITLE
Regression: Pasting into Datagrip TEXT field puts null

### ISSUE THREAD

**Issue by ydynnikov** [dolthub/dolt#6970] opened 2023-11-08 11:23 UTC
https://github.com/dolthub/dolt/issues/5735 is back

**Comment by timsehn** [comment] 2023-11-08 16:26
Sorry about this. @fulghum will look at this since he fixed it last time and it looks like we didn't have appropriate regression coverage.

**Comment by fulghum** [comment] 2023-11-08 19:18
Sorry that you hit this. I've got a repro set up with DataGrip and have captured wire traces with both Dolt and MySQL. I'm digging into what's different and will keep this issue updated.

**Comment by fulghum** [comment] 2023-11-08 20:03
Quick update... looking at the wire captures, I see that MySQL and Dolt are both sending the same max length for the `TEXT` field. That was the root cause of https://github.com/dolthub/dolt/issues/5735, so it seems something different is causing this paste error this time. 

I also found that the field metadata packets returned by Dolt are showing up as malformed in Wireshark, but I'm not sure why yet. This might be the root cause, but I'm surprised DataGrip wouldn't log an error if it encountered a malformed packet that it couldn't understand.

**Comment by ydynnikov** [comment] 2023-11-08 20:24
Hi Jason, let me know if you don't find a reason today - I'll dig into
DataGrip debugging tomorrow then

**Comment by fulghum** [comment] 2023-11-09 00:43
I made some more progress on this one. I think the malformed packets I mentioned earlier are just an issue with Wireshark. I'm _really_ skeptical that it's something that far off, since we would be seeing obvious errors in clients like `mysql` and DataGrip if it couldn't parse the packets. 

I noticed that although the field's max response length is the same for Dolt and MySQL, there is a different charset/collation ID being sent. When I hardcode Dolt to return the same charset/collation ID as MySQL is returning, I'm able to successfully paste in content to the spreadsheet table editor in DataGrip. 

I think the fix is to honor the [`character_set_results` system variable](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_results) when we're emitting the field metadata. I want to do a little more testing to make sure I understand MySQL's behavior here and also see why previous versions of Dolt were working correctly, since I don't think we've changed what charset we were sending. 

We're very close on this one now though and should be able to get a fix released tomorrow.

**Comment by fulghum** [comment] 2023-11-09 19:04
I've got PR https://github.com/dolthub/go-mysql-server/pull/2140 opened with a fix for this issue and I'm working on some final testing. The reason we regressed on this issue was because we were previously checking the field metadata for the max field length, but we weren't testing for the character set ID that DataGrip was expecting. I've got new tests that cover that now and I'm just doing some final validation against MySQL's behavior before pushing those tests up to the PR and marking it ready for review. We're still on track to get this fix released today.

**Comment by fulghum** [comment] 2023-11-09 22:10
The fix for this issue has now been released in [Dolt version 1.26.0](https://github.com/dolthub/dolt/releases/tag/v1.26.0). I've  manually tested with that version to validate that DataGrip will now allow you to paste into `TEXT` fields again.

Apologies again that you hit this error. Our tests were covering the length metadata, but not the character set metadata that's sent over the wire as part of the MySQL wire protocol. That has been fixed in our tests now, and in general, we're starting to move towards running more tests over the MySQL wire protocol, which will give us better coverage on these types of errors. 

Note that another change in this release needed to be released as a minor version change, and contains a feature version update, so once your database starts being used with this new Dolt version, other clients will also need to use this latest Dolt version once they pull/clone your database. We've also made sure to update the version DoltHub is using to make sure you all don't hit a snag there. 

Let us know if you hit any more issues and we'll be happy to help out!

**Closed by fulghum** 2023-11-09 22:10 UTC
Labels: bug, integrations, customer issue
