### ISSUE TITLE
Bad foreign key error message

### ISSUE THREAD

**Issue by bheni** [dolthub/dolt#3075] opened 2022-03-23 21:07 UTC
steps:

```bash
~/datasets>mkdir bug
~/datasets>cd bug
~/datasets/bug>dolt init
Successfully initialized dolt data repository.
~/datasets/bug>echo 'CREATE TABLE x (
>   id int PRIMARY KEY NOT NULL
> );
>
> CREATE TABLE y (
>   id int PRIMARY KEY NOT NULL
> );
>
> ALTER TABLE x ADD COLUMN x_id_fk int;
> ALTER TABLE x ADD FOREIGN KEY (x_id_fk) REFERENCES x(id) ON DELETE RESTRICT;
> ALTER TABLE x DROP COLUMN x_id_fk;' | dolt sql
```

output:
```bash
error on line 11 for query
ALTER TABLE x DROP COLUMN x_id_fk: cannot drop column `x_id_fk` as it is used in foreign key `10069`
cannot drop column `x_id_fk` as it is used in foreign key `10069`
```

**Comment by fulghum** [comment] 2022-03-24 15:55
Looks like this is consistent with MySQL's behavior. Here's what I get against MySQL: 
```
mysql> ALTER TABLE x DROP COLUMN x_id_fk;
ERROR 1828 (HY000): Cannot drop column 'x_id_fk': needed in a foreign key constraint 'x_ibfk_1'
```

**Comment by zachmu** [comment] 2022-03-29 18:50
Still a bug here, which is that the error message doesn't name the constraint (looks like it's using a tag value?)

**Comment by zachmu** [comment] 2022-03-29 19:03
Duplicate of https://github.com/dolthub/dolt/issues/3064

**Closed by zachmu** 2022-03-29 19:03 UTC
