### ISSUE TITLE
Cannot create another user with all privileges on a database

### ISSUE THREAD

**Issue by riccardolorenzon** [dolthub/dolt#6403] opened 2023-07-27 12:49 UTC
When connecting to a local dbms instance with the default `root` user, after creating a database and another user with `ALL` privileges, you cannot log in to the dbms with the `root` user, nor with the newly created user. 

The same happens when creating a `ROLE` and assigning `ALL` grants to that.

**Comment by timsehn** [comment] 2023-07-27 15:12
This is a duplicate of:

https://github.com/dolthub/dolt/issues/5759

The `root` user is automatically removed for security purposes once you add new users. The rationale is that you did not create it so you may not know it exists. It's potentially a bad choice and we're reassessing whether it's the right thing to do.

I'm resolving this in favor of the master issue.

**Closed by timsehn** 2023-07-27 15:12 UTC
Labels: bug, sql, customer issue

**Comment by bpf120** [comment] 2023-07-27 15:16
@riccardolorenzon , Thanks for filing. We'd love to learn about your Dolt use case too. You can [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.
