### ISSUE TITLE
GROUP BY on decimal type column gives incorrect result

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolt#4684] opened 2022-11-01 21:07 UTC
Query:
```
SELECT column_0, sum(column_1) FROM (values row(1.00,1), row(1.00,3), row(2,2), row(2,5), row(3,9)) a group by 1 order by 1;
```

Dolt (v0.50.12) result:
```
+----------+---------------+
| column_0 | sum(column_1) |
+----------+---------------+
| 1.00     | 1             |
| 1.00     | 3             |
| 2.00     | 7             |
| 3.00     | 9             |
+----------+---------------+
```

MySQL result:
```
+----------+---------------+
| column_0 | sum(column_1) |
+----------+---------------+
|     1.00 |             4 |
|     2.00 |             7 |
|     3.00 |             9 |
+----------+---------------+
```

**Comment by tanyongzhi** [comment] 2022-11-06 13:49
I did some digging, and found on the cause for this. The bug is really subtle, so I will try to be as detailed as possible here:

The issue lies in computing the grouping key in `sql/plan/group_by.go` in the `go-mysql-server` repo.

```
func groupingKey(
	ctx *sql.Context,
	exprs []sql.Expression,
	row sql.Row,
) (uint64, error) {
	hash := xxhash.New()
	for _, expr := range exprs {
		v, err := expr.Eval(ctx, row)
		if err != nil {
			return 0, err
		}
		_, err = hash.Write(([]byte)(fmt.Sprintf("%#v,", v)))
		if err != nil {
			return 0, err
		}
	}

	return hash.Sum64(), nil
}
```

More precisely, this line 

```
_, err = hash.Write(([]byte)(fmt.Sprintf("%#v,", v)))
```

computes the hash of the values in the group by column. When the value of the column (variable `v` in the source code) is an integer, the representation is consistent, and hence the hashed value would be the same for the same integers. However, when `v` is a decimal, it is actually a `decimal.Decimal` struct, which is defined as:

```
type Decimal struct {
	value *big.Int

	// NOTE(vadim): this must be an int32, because we cast it to float64 during
	// calculations. If exp is 64 bit, we might lose precision.
	// If we cared about being able to represent every possible decimal, we
	// could make exp a *big.Int but it would hurt performance and numbers
	// like that are unrealistic.
	exp int32
}
```

Because the `value` field in the struct is a pointer, it will differ for different instances of the same decimal value. 

As a result of this, the result of `fmt.Sprintf("%#v,", v)` will be different, resulting in the hash result for to be different, causing the groupby to fail. Again, the root cause of this is  **different** instances of `decimal.Decimal` structs with the **same** underlying numerical value.

I can think of a few ways to solve this issue:

1.  Add separate logic for `decimal.Decimal` types in `groupingKey`. This is probably the most straightforward way to resolve this bug, but it is not general at all. The same problem might arise for other structs in the future.
2. Change the hash input from `%#v` to `%v`. This will result in a default representation for the structs, instead of the golang default representation which prints the pointer (the `value` field).

Please feel free to comment on the above solutions, or suggest any other possible fixes for this bug!

**Comment by fulghum** [comment] 2022-11-07 16:54
Nice work digging into this one @tanyongzhi! Your analysis looks correct to me. Thanks for figuring out what was going on here and suggesting some paths forward. 🙏 

I like the second suggestion you made (using `%#v` to format key values), but I'm not convinced that it'll give the right hash key... I'm guessing that the pointer value for `*big.Int` would still be used, but it's worth a quick test for sure. If that approach works, great; if not, I think you're right that we'd need to special case `decimal.Decimal` and convert to a canonical string. 

Thanks again for taking the time to dig into this one!

**Comment by tanyongzhi** [comment] 2022-11-08 05:35
Thanks, Jason!

The second suggestion seems to work. I think this is because the `decimal` struct implements the `Stringer` interface, hence it does not print the pointer value when printed using the `%v` specifier.

I've created a PR for this issue [here](https://github.com/dolthub/go-mysql-server/pull/1388). Please have a look!

**Comment by timsehn** [comment] 2022-11-08 16:20
Amazing! Thanks @tanyongzhi.

**Comment by fulghum** [comment] 2022-11-08 17:01
Nice job debugging through this one and coming up with such a simple, clear fix! 👏 Thank you @tanyongzhi!

**Comment by fulghum** [comment] 2022-11-09 16:42
Many thanks to @tanyongzhi for contributing this fix! 🎉  It's been merged into main for `go-mysql-server` and we'll get it into `dolt` today. After that, it'll go out in the next `dolt` release, likely by the end of this week.

**Closed by fulghum** 2022-11-09 16:42 UTC
Labels: bug, sql, good-repro
