### ISSUE TITLE
Feature request:  Optimize initialization for large databases

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#5019] opened 2022-12-17 19:30 UTC
I have a small script in my .bashrc file that shows the current branch in the command prompt.  Thus, every time a prompt is generated, `dolt branch --show-current` is run.  This takes about 60 seconds for a database the size of the housing bounty database (~100GB ?).  Thus, whenever this database is in a sub-directory, working on the command line becomes a PITA.

As a quick fix, I'm wondering if dolt needs to be fully initialized for every command.  Could this be bypassed for things like branch, which really doesn't make sense to even run outside the database directory?

**Comment by timsehn** [comment] 2023-02-10 01:08
This is a duplicate of #3629. Resolving in favor of that one.

**Closed by timsehn** 2023-02-10 01:08 UTC
Labels: bug, performance, cli

**Comment by lizkimble** [comment] 2023-05-04 15:00
i'd like to revisit this, it's so useful knowing what branch you're on by looking at the command prompt, but when the database is large it really becomes a painfully slow

is there some other way to get the current branch, like from the repo_state.json file
