### ISSUE TITLE
Segfault when querying inconsistent windows

### ISSUE THREAD

**Issue by swaldman** [dolthub/dolt#4739] opened 2022-11-09 21:59 UTC
If you simultaneously request an unqualified, ungrouped aggregate function (which wants to return one row) and a window function (which wants to show one per row) `dolt`, in its understandable unhappiness, segfaults.

Here's the right thing:

```
$ dolt init
Successfully initialized dolt data repository.
$ dolt sql -q "CREATE TABLE OOPSIE (num INTEGER, val DOUBLE)"
$ dolt sql -q "INSERT INTO OOPSIE VALUES (1, 0.01), (2,0.5)"
Query OK, 2 rows affected (0.00 sec)
$ dolt sql -q "SELECT AVG(val) OVER w, LAST_VALUE(val) OVER w FROM OOPSIE WINDOW w AS (ORDER BY num RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)"
+-----------------+------------------------+
| AVG(val) OVER w | LAST_VALUE(val) OVER w |
+-----------------+------------------------+
| 0.255           | 0.5                    |
| 0.255           | 0.5                    |
+-----------------+------------------------+
```

Here's the oopsie:

```
$ dolt sql -q "SELECT AVG(val), LAST_VALUE(val) OVER w FROM OOPSIE WINDOW w AS (ORDER BY num RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e9b1b7]

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression/function/aggregation.(*AvgAgg).WithWindow(0xc00109e958, 0x0)
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/expression/function/aggregation/window_functions.go:158 +0x77
github.com/dolthub/go-mysql-server/sql/expression/function/aggregation.(*Avg).NewWindowFunction(0xc000b73a90)
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/expression/function/aggregation/unary_aggs.og.go:66 +0x7a
github.com/dolthub/go-mysql-server/sql/plan.windowToIter(0xc0010b67e0)
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/plan/window.go:155 +0x1bc
github.com/dolthub/go-mysql-server/sql/plan.(*Window).RowIter(0xc0010b67e0, 0x2aec6c0?, {0x0?, 0xc0002c8d20?, 0x1?})
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/plan/window.go:129 +0x53
github.com/dolthub/go-mysql-server/sql/plan.(*Project).RowIter(0xc0010b6810, 0x2eba060?, {0x0, 0x0, 0x0})
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/plan/project.go:69 +0x25d
github.com/dolthub/go-mysql-server/sql/plan.(*TransactionCommittingNode).RowIter(0xc00013cfe0, 0xc00109ef98?, {0x0?, 0x22257c5?, 0xc000b72b90?})
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/plan/transaction_committing_iter.go:59 +0x32
github.com/dolthub/go-mysql-server/sql/plan.(*QueryProcess).RowIter(0xc000b60ac8, 0x2ece568?, {0x0?, 0x9?, 0x2eb58f0?})
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/sql/plan/process.go:66 +0x38
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0x0?, 0xc0005acb40, {0xc000354bd0, 0x88}, {0x0?, 0x0?}, 0xc000d2c000?)
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/engine.go:226 +0x2ba
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/engine.go:158
github.com/dolthub/go-mysql-server.(*Engine).Query(0x88?, 0xc00109f190?, {0xc000354bd0?, 0xe8?})
	/Users/swaldman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221104210111-b924baa9d052/engine.go:153 +0x26
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(...)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/commands/engine/sqlengine.go:255
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0xc000354bd0?, {0xc000354bd0?, 0x88?}, 0xc000354bd0?, {0x2e98240?, 0xc000140000?})
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/commands/sql.go:1245 +0x3d3
github.com/dolthub/dolt/go/cmd/dolt/commands.runMultiStatementMode(0xc000b725f0?, 0xc000593380, {0x2e8f6a0?, 0xc0000b21a0}, 0x0)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/commands/sql.go:830 +0x41d
github.com/dolthub/dolt/go/cmd/dolt/commands.execMultiStatements({0x2ea4d78, 0xc000b50780}, 0x30?, 0x8?, {0x2e8f6a0, 0xc0000b21a0}, 0x1?, 0xc00109f720)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/commands/sql.go:587 +0x1d9
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode({0x2ea4d78, 0xc000b50780}, 0x5?, 0x3f250c0?, 0xc000126d50, {0x7ff7bfeff7fc, 0x88}, 0x78?, 0xc0000061a0?, 0xc00109f720)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/commands/sql.go:451 +0x245
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x2ae10dd?, 0xc000bbf820?}}, {0x2ea4d78, 0xc000b50780}, {0xc000a20400, 0x8}, {0xc0000520a0, 0x2, 0x2}, 0xc000b74000)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/commands/sql.go:304 +0x130b
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2add12f, 0x4}, {0x2af6fa1, 0x11}, {0x0, 0x0}, {0xc0005d4000, 0x2f, 0x2f}, 0x0}, ...)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/cli/command.go:237 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2add12f, 0x4}, {0x2af6fa1, 0x11}, {0x0, 0x0}, {0xc0005d4000, 0x2f, 0x2f}, 0x0}, ...)
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/cli/command.go:186 +0x47e
main.runMain()
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/dolt.go:395 +0x7a5
main.main()
	/Users/swaldman/development/contrib-git/dolt/go/cmd/dolt/dolt.go:140 +0x19
```

**Comment by timsehn** [comment] 2022-11-09 22:11
Thanks. We'll make it not panic.

**Comment by swaldman** [comment] 2022-11-09 22:12
(…if only you could do that for me.)

**Comment by fulghum** [comment] 2022-11-09 22:23
Nice find @swaldman! Thanks for reporting this; that panic is nasty! 😭 I was able to repro with dolt version 0.50.13. 

Here's the error message MySQL returns for this query: 
```
ERROR 1140 (42000): In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'dolt.OOPSIE.val'; this is incompatible with sql_mode=only_full_group_by
```

Looks like dolt is missing some error handling here. We'll dig in and get this patched so that dolt behaves like MySQL and returns the same error.

**Comment by fulghum** [comment] 2022-11-10 01:50
I've got a first pass on validation logic that will detect 1) if an aggregate function is being used without an explicit `group by`  grouping (meaning there's an implicit, single group of all rows) and 2) if there are illegal uses of non-aggregated columns (such as in the projected window functions in the example above). 

It matches MySQL's error message above and I've confirmed that no other tests in the test suite are impacted from this change, but it still needs to be cleaned up a bit and tested a little more. I'll get it cleaned up and will have it out for review tomorrow.

**Comment by fulghum** [comment] 2022-11-10 22:45
I got the improved validation and new error message change merged into main on `go-mysql-server`. We'll pick up that new dependency version for Dolt next, then get this published in the next Dolt release. That'll likely be early next week, although I'm more than happy to run a release sooner if you'd like it. I'll follow up and resolve this issue once that Dolt release goes out. 

Thanks again for taking the time to bring this one to our attention! 🙏

**Comment by fulghum** [comment] 2022-11-16 01:14
This fix is out in the latest versions of Dolt now. 

Resolving this one now; please keep the great feedback and bug reports coming! 🙏

**Closed by fulghum** 2022-11-16 01:14 UTC
Labels: bug, panic, good-repro
