### ISSUE TITLE
Cannot use column names containing spaces or uppercase characters as a generated primary key

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#7388] opened 2024-01-22 19:46 UTC
## Issue

Dolt cannot use a generated column based on column names containing spaces as a primary key.

## Reproduction

```sh
# Run temporary environment
docker run --rm -it --entrypoint bash dolthub/dolt:1.22.0 -c bash

dolt config --global --add user.email "test@test.com"
dolt config --global --add user.name "test"
dolt init

dolt sql -q 'CREATE TABLE test (
  `First Name` TEXT,
  Region TEXT,
  id VARCHAR(255) GENERATED ALWAYS AS (CONCAT(`First Name`, "_", `Region`)) STORED
);
ALTER TABLE `test`
ADD PRIMARY KEY (id);'

dolt add -A
dolt commit -m "add table"
```

## Versions tested

Dolt 1.22.0: ✅ Pass
Dolt 1.23.0: ✅ Pass
Dolt 1.24.0: ❌ Fail

```
error on line 6 for query 
ALTER TABLE `test`
ADD PRIMARY KEY (id): Invalid default value for '(concat(First Name,'_',Region))': syntax error at position 26 near 'Name'
```

Dolt 1.32.0 ❌ Fail (same error as above)

## Related issues & workaround

- #7316 - Perhaps there's limited test coverage when it comes to using columns that contain uppercase or space characters. To work around this, I'll be refactoring my project to use `snake_case` column names.

Workaround:

```sh
dolt sql -q 'CREATE TABLE test (
  first_name TEXT,
  region TEXT,
  id VARCHAR(255) GENERATED ALWAYS AS (CONCAT(first_name, "_", region)) STORED
);
ALTER TABLE `test`
ADD PRIMARY KEY (id);'
```

The workaround above does work in Dolt 1.32.0.

**Comment by timsehn** [comment] 2024-01-22 19:49
So are you saying this was broken in 1.24.0 and now is fixed and working in 1.32.0?

**Comment by timsehn** [comment] 2024-01-22 19:50
Oh I see, the workaround works in 1.32.0. @max-hoffman will triage this.

**Comment by theetrain** [comment] 2024-01-22 19:51
> Oh I see, the workaround works in 1.32.0.

That's right, I updated the report to clarify.

**Comment by jycor** [comment] 2024-01-22 20:09
Hey @theetrain,

It looks like the issue is related to our `String()` method used for default values.
Another workaround is to use single quotes in the `CONCAT()`.

```sql
tmp/main*> create table test (`ABC def` text, xyz text, id varchar(255) generated always as (concat('ABC def', "_", xyz)) stored);
tmp/main*> show create table test;
+-------+----------------------------------------------------------------------------+
| Table | Create Table                                                               |
+-------+----------------------------------------------------------------------------+
| test  | CREATE TABLE `test` (                                                      |
|       |   `ABC def` text,                                                          |
|       |   `xyz` text,                                                              |
|       |   `id` varchar(255) GENERATED ALWAYS AS (concat('ABC def','_',xyz)) STORED |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin           |
+-------+----------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Note that this was through the `dolt sql` shell.
It looks like you're using `dolt sql -q '...'` with single quotes. You will probably have to escape the single quotes inside the single quotes or use double quotes instead `dolt sql -q "..."`

In the meantime, we're working on getting the original query with backquotes working.

**Comment by zachmu** [comment] 2024-01-22 20:14
That workaround doesn't work: `First Name` is not a string, it's the name of a column. Needs to be fixed in dolt, or use the original workaround of not putting a space in the column name.

**Closed** 2024-01-24 23:22 UTC
Labels: bug, analyzer, customer issue, correctness

**Comment by jycor** [comment] 2024-01-25 10:21
Hey @theetrain, the fix for this has been merged to main. 
We'll cut a release for you later today.

**Comment by theetrain** [comment] 2024-01-25 15:55
Thank you!

**Comment by bpf120** [comment] 2024-01-31 21:10
@theetrain , great to see you are still using Dolt, and thanks for filing this. We'd love to catch up on your Dolt use case sometime. Feel free to [email me](mailto:brianf@dolthub.com) or say hi on [Discord](https://discord.gg/gqr7K4VNKe) the next time you are on.
