### ISSUE TITLE
Trying to connect with DBeaver to sql-server results in panic of sql-server

### ISSUE THREAD

**Issue by rklec** [dolthub/dolt#2492] opened 2021-12-13 10:21 UTC
## STRs

Import some bigger CSV file (~4 KB):
```
dolt init
dolt config .. # the username/mail stuff
dolt table import ***  -c .\****.csv --delim=";"
```

That all worked (after I noticed I had to add the `--delim`).

Now I started the sql server, which also works and try to connect using [DBeaver](https://dbeaver.io/):
```
$ dolt sql-server
Starting server with Config HP="localhost:3306"|U="root"|P=""|T="28800000"|R="false"|L="info"
```

These are just the default connection details:
![grafik](https://user-images.githubusercontent.com/71322635/145794241-174a6afe-b298-4a3d-abb4-638e9f920b2d.png)

(Before the first connection, it asks me to download some "drivers" or whatever, which I confirm.)

### What should happen

Connect. (Or at least a useful error and not a "panic" 😲 )

### What happens

![grafik](https://user-images.githubusercontent.com/71322635/145794347-6d357c72-1664-49ca-80a3-144f6c4a5f25.png)

> Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

Details there:
```
SQL-Fehler [08003]: No operations allowed after connection closed.
  No operations allowed after connection closed.
  No operations allowed after connection closed.
    Communications link failure

The last packet successfully received from the server was 2 milliseconds ago.  The last packet sent successfully to the server was 2 milliseconds ago.
    Communications link failure

The last packet successfully received from the server was 2 milliseconds ago.  The last packet sent successfully to the server was 2 milliseconds ago.
      Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
      Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
```

And in the terminal with dolt:
```
2021-12-13T11:18:32+01:00 INFO [conn 1] NewConnection {DisableClientMultiStatements=false}
2021-12-13T11:18:32+01:00 INFO [conn 2] NewConnection {DisableClientMultiStatements=false}
2021-12-13T11:18:32+01:00 INFO [conn %!d(<nil>)] kill query: pid 14 {}
2021-12-13T11:18:32+01:00 INFO [conn 2] ConnectionClosed {}
2021-12-13T11:18:32+01:00 ERROR [conn %!d(<nil>)] mysql_server caught panic:
unexpected type
/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211207215525-80e72ca0e014/sql/numbertype.go:679 (0x116c70a)
/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211207215525-80e72ca0e014/sql/numbertype.go:349 (0x116c4af)
/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211207215525-80e72ca0e014/server/handler.go:691 (0x1dceb4c)
/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211207215525-80e72ca0e014/server/handler.go:424 (0x1dcd384)
/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211207215525-80e72ca0e014/server/handler.go:548 (0x1dce4bd)
/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211207215525-80e72ca0e014/server/handler.go:150 (0x1dcac45)
/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20211206222232-14a8101b8243/go/mysql/conn.go:1252 (0x109608f)
/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20211206222232-14a8101b8243/go/mysql/conn.go:852 (0x1092618)
/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20211206222232-14a8101b8243/go/mysql/server.go:478 (0x10ab793)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0xc0aae0)
 {}
2021-12-13T11:18:32+01:00 INFO [conn 1] ConnectionClosed {}
```

## Screenshot

![grafik](https://user-images.githubusercontent.com/71322635/145793390-795e497b-ca8b-4498-98aa-5041666e9454.png)

## System

DBeaver 21.3.1
Dolt v0.34.8

All installed via chocolately.

Windows 10 v10.0.19042 Build 19042

## Edit

Ah, when I `dump` the DB, it has some strange character in there:
```
DROP TABLE IF EXISTS `***`;
CREATE TABLE `***` (
  `﻿A****`
```
![grafik](https://user-images.githubusercontent.com/71322635/145796142-f681c047-6a92-490f-909d-076236042b97.png)

**Comment by VinaiRachakonda** [comment] 2021-12-13 22:30
Hi @rklec, we think we found the cause of the problem. We will get a fix out soon

**Comment by VinaiRachakonda** [comment] 2021-12-14 00:27
This is now merged in master

**Comment by timsehn** [comment] 2021-12-15 19:51
This fix should be in today's release.

**Closed by timsehn** 2021-12-15 19:51 UTC
