### ISSUE TITLE
"optimistic lock failed on database Root update"

### ISSUE THREAD

**Issue by ckaran** [dolthub/dolt#3184] opened 2022-04-07 19:12 UTC
I'm getting the error "optimistic lock failed on database Root update" whenever I try to clone a dolt repository that is local (on my file system).

What I tried and what I got:

```bash
cfkaran2@Hammer:~/Documents/repositories/experiments/dolt_experiments$ mkdir foo
cfkaran2@Hammer:~/Documents/repositories/experiments/dolt_experiments$ cd foo/
cfkaran2@Hammer:~/Documents/repositories/experiments/dolt_experiments/foo$ dolt init
Successfully initialized dolt data repository.
cfkaran2@Hammer:~/Documents/repositories/experiments/dolt_experiments/foo$ cd ..
cfkaran2@Hammer:~/Documents/repositories/experiments/dolt_experiments$ pwd
/home/cfkaran2/Documents/repositories/experiments/dolt_experiments
cfkaran2@Hammer:~/Documents/repositories/experiments/dolt_experiments$ dolt clone file:/home/cfkaran2/Documents/repositories/experiments/dolt_experiments/foo/.dolt/noms/ bar
cloning file:///home/cfkaran2/Documents/repositories/experiments/dolt_experiments/foo/.dolt/noms
6 of 6 chunks complete. 0 chunks being downloaded currently.
optimistic lock failed on database Root update
```

**Comment by timsehn** [comment] 2022-04-07 21:32
I don't think we support renaming the repo like `dolt clone foo bar`. try going to a different directory where foo isn't there?

**Comment by ckaran** [comment] 2022-04-07 21:38
I was in the parent directory of `foo`.  I suspect that cloning requires cloning the `nom` directory within the database, correct?

**Comment by timsehn** [comment] 2022-04-07 21:48
I thought the problem is clone tries to create another directory `foo` as appending `bar` to the command is a no-op but i was wrong. 
```
dolt $ pwd
/Users/timsehn/liquidata/dolt
dolt $ mkdir ckeran
dolt $ cd ckeran
ckeran $ dolt init
Successfully initialized dolt data repository.
ckeran $ cd ..
dolt $ dolt clone file:/Users/timsehn/liquidata/dolt/ckeran/.dolt/noms
cloning file:///Users/timsehn/liquidata/dolt/ckeran/.dolt/noms
6 of 6 chunks complete. 0 chunks being downloaded currently.
optimistic lock failed on database Root update
dolt $ cd /tmp
tmp $ dolt clone file:/Users/timsehn/liquidata/dolt/ckeran/.dolt/noms
cloning file:///Users/timsehn/liquidata/dolt/ckeran/.dolt/noms
6 of 6 chunks complete. 0 chunks being downloaded currently.
optimistic lock failed on database Root update
```
It seems this clone an existing noms directory thing has got even more broken since we don't test it.

The best way to work with a file remote is do something like:
```
mkdir mydb
cd mydb
dolt init
dolt remote add origin file:/tmp
dolt push origin master
cd /some/dir/
dolt clone file:/tmp/mydb
```

**Comment by ckaran** [comment] 2022-04-08 12:09
> It seems this clone an existing noms directory thing has got even more broken since we don't test it.

Ouch... I think this needs to be tested and fixed.  Since dolt advertises itself as 'git for data', and it tries to supply the same set of commands, it really feels like a drop-in replacement.  So when things like this don't work, it's concerning.

**Comment by zachmu** [comment] 2022-04-08 18:33
Yup, definitely. We'll get this fixed.

In the meantime, you should be able to use a named remote.

**Comment by ckaran** [comment] 2022-04-08 19:27
Thanks!

**Comment by JCOR11599** [comment] 2022-04-14 17:03
The fix for this has been merged to main. Would you like us to do a release?

**Closed by JCOR11599** 2022-04-14 17:03 UTC
Labels: bug

**Comment by ckaran** [comment] 2022-04-14 18:37
@JCOR11599, if you're asking me, I'm fine either way.  I'm not yet relying on Dolt for anything, just evaluating it, so do a release when you think it's appropriate.

**Comment by timsehn** [comment] 2022-04-14 18:39
Cool. It will go out tomorrow or Monday.
