### ISSUE TITLE
Support more revision spec in database names

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#2146] opened 2021-09-16 22:40 UTC
These work:

```sql
show create table `test/0i4vscdluqolq3p6p8qrq5te916sr7c4`.foo;
show create table `test/feature-branch`.foo;
```

But any revision spec should be possible with the same syntax (these fail now):

```sql
show create table `test/HEAD~2`.foo;
show create table `test/feature-branch^`.foo;
```

**Comment by timsehn** [comment] 2021-09-16 22:42
As we've discussed `as of` here is not in the SQL standard and will require a fork of Vitess.

**Comment by andrew-wm-arthur** [comment] 2021-09-22 20:34
I'm not completely sold that we should support all rev specs. Do you have a use case in mind?

**Comment by timsehn** [comment] 2022-08-24 01:11
@fulghum you just touched rev specs. Do you think this issue is still valid?

**Comment by fulghum** [comment] 2022-08-24 20:27
Yup, I still wanna add in support for these to round out ways to reference a revision of a database. I was tracking this through https://github.com/dolthub/dolt/issues/3086, but this looks like a better tracking issue, so I'll resolve the other one as a duplicate of this one.

**Closed** 2022-08-26 23:38 UTC
