### ISSUE TITLE
In multi head mode, sometimes feature branch editing has an influence on main branch

### ISSUE THREAD

**Issue by liuqianhong6007** [dolthub/dolt#2415] opened 2021-11-18 09:10 UTC
My workflow as followed

1. Create a database connection and switch it to feature branch

2. Start a transaction with "BEGIN" statement

3. Create a new table or update an existent table, and "ROLEBACK" if failed

4. Commit this transtraction with "COMMIT" statement

5. Start another transtraction with "BEGIN" statement

6. Use "SELECT DOLT_ADD('xxx')" to add table to the staged, and "ROLEBACK" if failed

7. Use "SELECT DOLT_COMMIT('-m','xxx')" to commit table changes, and "ROLEBACK" if failed

8. Commit this transtraction with "COMMIT" statement

After above operation, I can see the commit log in the feature branch, but sometimes it's rather strange that using "dolt status"  I can see the table also appeared but unchtracked state in the main branch, which means that main branch has been dirty.

Have any idea about that ?

**Comment by zachmu** [comment] 2021-11-23 00:23
What you're describing shouldn't be possible, so I'm not sure what's going on. Can you give us exact steps to reproduce this? Are you seeing the `main` branch as dirty on the command line?

**Comment by andrew-wm-arthur** [comment] 2021-12-06 18:53
@liuqianhong6007 are you still experiencing this issue?

**Comment by timsehn** [comment] 2022-08-03 22:40
Resolving due to lack of info.

**Closed by timsehn** 2022-08-03 22:40 UTC
