### ISSUE TITLE
push to google storage gives me a strange error 

### ISSUE THREAD

**Issue by zzztimbo** [dolthub/dolt#893] opened 2020-09-21 06:46 UTC
What am I to make of this? 

```
➜  dolt push --set-upstream sesame_pricebooks_dolt_gs master
Counted chunks: 158110, Buffered chunks: 158110)

error: push failed
cause: manifest
```

**Comment by zachmu** [comment] 2020-11-16 16:35
Brian, any ideas what the cause of the error is here?

**Comment by VinaiRachakonda** [comment] 2021-07-16 23:24
Closing this for now. We've had people successfully push to gcs recently who have had no issues. There's been some good work on this done

**Closed by VinaiRachakonda** 2021-07-16 23:24 UTC
