### ISSUE TITLE
unexpected dolt sql console crash

### ISSUE THREAD

**Issue by rbasa** [dolthub/dolt#5000] opened 2022-12-15 17:21 UTC
When joining two tables, my dolt sql terminal gives me an error and closes.
This query was supported on versions < 0.51.11
My db is migrated, you can check the repo on https://www.dolthub.com/repositories/bitfinex/securities-analysis/data/main/debt_asset_market

Repro:

$ dolt clone bitfinex/securities-analysis
cloning https://doltremoteapi.dolthub.com/bitfinex/securities-analysis
$ cd securities-analysis 
$ dolt sql <<SQL 
heredoc>         select
          symbol,
          timestamp,
          usd_price as close
        from
          primary_market pm
        inner join
          asset
        on
          asset.asset_id = pm.asset_id
heredoc> SQL
panic: cannot write NULL to non-NULL field

goroutine 261 [running]:
github.com/dolthub/dolt/go/store/val.(*TupleBuilder).Build(0xc0006d55d0?, {0x2eef818?, 0x3e8aee0?})
    /Users/timsehn/dolthub/git/dolt/go/store/val/tuple_builder.go:58 +0x85
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.prollyKeylessIndexIter.queueRows({{0x2f1c2a0, 0xc0009930a0}, {0x2ee4f60, 0xc000b98900}, {{{{...}, {...}, 0x3, 0x0, 0x0, {...}}, ...}, ...}, ...}, ...)
    /Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/prolly_index_iter.go:444 +0x125
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.newProllyKeylessIndexIter.func1()
    /Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/prolly_index_iter.go:407 +0x58
golang.org/x/sync/errgroup.(*Group).Go.func1()
    /Users/timsehn/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
    /Users/timsehn/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

**Comment by timsehn** [comment] 2022-12-15 17:23
I can reproduce.

**Comment by timsehn** [comment] 2022-12-15 17:31
Thought it might be an alias issue but removing aliases no help
```
$ dolt sql <<SQL 
        select
          symbol,
          timestamp,
          usd_price         
        from
          primary_market
        inner join
          asset
        on
          asset.asset_id = primary_market.asset_id
SQL
panic: cannot write NULL to non-NULL field

goroutine 274 [running]:
github.com/dolthub/dolt/go/store/val.(*TupleBuilder).Build(0xc000629540?, {0x2eef818?, 0x3e8aee0?})
	/Users/timsehn/dolthub/git/dolt/go/store/val/tuple_builder.go:58 +0x85
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.prollyKeylessIndexIter.queueRows({{0x2f1c2a0, 0xc0006810a0}, {0x2ee4f60, 0xc000b42300}, {{{{...}, {...}, 0x3, 0x0, 0x0, {...}}, ...}, ...}, ...}, ...)
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/prolly_index_iter.go:444 +0x125
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.newProllyKeylessIndexIter.func1()
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/prolly_index_iter.go:407 +0x58
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/timsehn/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/timsehn/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by timsehn** [comment] 2022-12-15 17:36
Suspect this is related to primary_market being a keyless table:
```
primary_market @ working
CREATE TABLE `primary_market` (
  `timestamp` timestamp NOT NULL,
  `asset_id` int NOT NULL,
  `asset_amount` decimal(25,10),
  `currency_id` int NOT NULL,
  `currency_amount` decimal(25,10),
  `effective_price` decimal(25,10),
  `usd_price` decimal(25,10),
  KEY `asset_id` (`asset_id`),
  KEY `currency_id` (`currency_id`),
  CONSTRAINT `2hi2a91k` FOREIGN KEY (`currency_id`) REFERENCES `currency` (`currency_id`),
  CONSTRAINT `6j5kbjgo` FOREIGN KEY (`asset_id`) REFERENCES `asset` (`asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
```

**Comment by fulghum** [comment] 2022-12-15 17:47
Great catch on the lack of a primary key. I was able to alter the table to add a primary key and then the query works correctly:

```sql
alter table primary_market add primary key (timestamp, asset_id, currency_id);

 select symbol, timestamp, usd_price from primary_market inner join asset on asset.asset_id = primary_market.asset_id;
+--------+-------------------------+-------------------+
| symbol | timestamp               | usd_price         |
+--------+-------------------------+-------------------+
| BMNUSD | 2022-01-26 02:28:35.18  | 301104.6400000000 |
| BMNUSD | 2022-01-26 14:58:28.275 | 305055.5841632000 |
| BMNUSD | 2022-02-07 08:23:43.306 | 307651.1274145900 |
+--------+-------------------------+-------------------+
3 rows in set (0.00 sec)
```

**Comment by fulghum** [comment] 2022-12-15 17:49
@rbasa – as a workaround, are you able to run the alter statement above to get unblocked? 

We still need to dig into the panic a little deeper, but wanted to make sure you had a usable workaround while we keep digging.

**Comment by rbasa** [comment] 2022-12-15 17:50
But adding this pk constrain isnt very accurate, since several trades might occure at the same moment, regarding the same symbol

**Comment by fulghum** [comment] 2022-12-15 17:54
Makes sense. If you need an immediate workaround, we can help you come up with a reasonable and safe primary key (e.g. adding a new column with a unique id is one option). We're still digging in for the root cause fix, just wanted to see how we can help unblock you as fast as possible.

**Comment by fulghum** [comment] 2022-12-15 18:29
I've been working on reproing this in the debugger, but haven't been able to create a new database with this same structure/data that will trigger this issue yet... 

With the latest released dolt version (0.51.14), I did notice that dropping the keys on `primary_market` and then re-adding them makes this query stop crashing. My hypothesis is that there may be a problem in the index and rebuilding it fixes it. 

Still digging deeper...

**Comment by fulghum** [comment] 2022-12-15 18:48
Alright... I've got a better workaround for you that doesn't require adding a primary key to the `primary_market` table. The commands below will rebuild the keys on that table

```sql
alter table primary_market drop constraint 2hi2a91k;
securities_analysis> alter table primary_market drop constraint 6j5kbjgo;
securities_analysis> alter table primary_market drop key asset_id;
securities_analysis> alter table primary_market drop key currency_id;
securities_analysis> alter table primary_market add  KEY `asset_id` (`asset_id`);
securities_analysis> alter table primary_market add  KEY `currency_id` (`currency_id`);
securities_analysis> alter table primary_market add CONSTRAINT `2hi2a91k` FOREIGN KEY (`currency_id`) REFERENCES `currency` (`currency_id`);
securities_analysis> alter table primary_market add CONSTRAINT `6j5kbjgo` FOREIGN KEY (`asset_id`) REFERENCES `asset` (`asset_id`);
securities_analysis>  
```

After that, I'm able to run: 
```sql
 select symbol, timestamp, usd_price from primary_market inner join asset on asset.asset_id = primary_market.asset_id;
+--------+-------------------------+-------------------+
| symbol | timestamp               | usd_price         |
+--------+-------------------------+-------------------+
| BMNUSD | 2022-01-26 02:28:35.18  | 301104.6400000000 |
| BMNUSD | 2022-01-26 14:58:28.275 | 305055.5841632000 |
| BMNUSD | 2022-02-07 08:23:43.306 | 307651.1274145900 |
+--------+-------------------------+-------------------+
3 rows in set (0.00 sec)
```

I synced up with a teammate and the root cause is a merge issue that we are already in the process of fixing. 

Let us know if you have any issues with the workaround above and apologies for this snag you hit!

**Comment by fulghum** [comment] 2022-12-16 19:04
Resolving this one since it sounds like we got things working for you again. Please let us know if you hit any other snags and we'll be happy to jump on them asap.

**Closed by fulghum** 2022-12-16 19:04 UTC
Labels: bug, panic, good-repro
