### ISSUE TITLE
`call dolt_merge('branch1', 'branch2')` should either merge `branch1` and `branch2` or fail not silently ignore the `branch2` argument.

### ISSUE THREAD

**Issue by lmy1218** [dolthub/dolt#5729] opened 2023-04-12 06:04 UTC
No changes are found by querying with select * from dolt_status.

**Comment by timsehn** [comment] 2023-04-12 15:39
I think we need a bit more information here but we'd love to help. Are you trying to merge from the command line or in the SQL server?

**Comment by bpf120** [comment] 2023-04-12 15:56
@lmy1218, we'd love to learn more about your Dolt use case too. You can [email](mailto:brianf@dolthub.com) me or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you would like to share. Thanks for trying Dolt.

**Comment by lmy1218** [comment] 2023-04-13 01:53
I have two branches, dev and dev_1001. When I initiate a merge from the main branch using "call dolt_merge('dev', 'dev_1001')", an error will be reported: "cannot merge with uncommitted changes". I tried to use "select * from dolt_status" to query but did not get any results. However, after I switched to the dev_1001 branch using "call dolt_checkout('dev_1001')", the merge can be initiated normally. Thank you very much for your answer。




?木有あいじょう
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dolthub/dolt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dolthub/dolt] cannot merge with uncommitted changes (Issue #5729)





 
I think we need a bit more information here but we'd love to help. Are you trying to merge from the command line or in the SQL server?

**Comment by timsehn** [comment] 2023-04-13 15:02
Thanks for the repro steps. I will try and reproduce on my end and get back to you.

**Comment by timsehn** [comment] 2023-04-13 16:53
So, I thought this might be a problem with having uncommitted changes on the other branch but was not able to repro that way. 

Starting from a fresh server this is what I tried:
```
mysql> create table t (pk int primary key, c1 int, c2 int);
Query OK, 0 rows affected (0.02 sec)

mysql> call dolt_add('t');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.01 sec)

mysql> call dolt_commit('-m', 'Created table');
+----------------------------------+
| hash                             |
+----------------------------------+
| os1s2dal2ci81lebergosvupbubvu9gf |
+----------------------------------+
1 row in set (0.02 sec)

mysql> call dolt_branch('branch1');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.02 sec)

mysql> call dolt_branch('branch2');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.02 sec)

mysql> call dolt_checkout('branch2');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.01 sec)

mysql> insert into t values (0,0,0);
Query OK, 1 row affected (0.01 sec)

mysql> call dolt_checkout('branch1');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.00 sec)

mysql> call dolt_merge('branch2');
+--------------+-----------+
| fast_forward | conflicts |
+--------------+-----------+
|            1 |         0 |
+--------------+-----------+
1 row in set, 1 warning (0.01 sec)

mysql> call dolt_checkout('branch2');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set, 1 warning (0.00 sec)

mysql> insert into t values (1,1,1);
Query OK, 1 row affected (0.01 sec)

mysql> call dolt_checkout('branch1');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.00 sec)

mysql> insert into t values (2,2,2);
Query OK, 1 row affected (0.01 sec)

mysql> call dolt_commit('-am', 'inserted 2s');
+----------------------------------+
| hash                             |
+----------------------------------+
| 2299a1rt444me94jd5foac4d1nq8m7l2 |
+----------------------------------+
1 row in set (0.01 sec)

mysql> call dolt_merge('branch2');
+--------------+-----------+
| fast_forward | conflicts |
+--------------+-----------+
|            0 |         0 |
+--------------+-----------+
1 row in set, 1 warning (0.01 sec)

mysql> seelct * from t;
ERROR 1105 (HY000): syntax error at position 7 near 'seelct'
mysql> select * from t;
+------+------+------+
| pk   | c1   | c2   |
+------+------+------+
|    2 |    2 |    2 |
+------+------+------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------+
| Level   | Code | Message                                                   |
+---------+------+-----------------------------------------------------------+
| Warning | 1105 | current fast forward from a to b. a is ahead of b already |
+---------+------+-----------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql>
```

This seems to be working as expected. 

Upon typing this, I see you are using two arguments to merge. I will try that.

**Comment by timsehn** [comment] 2023-04-13 16:59
So, I think I found the issue. `call dolt_merge('branch1', 'branch2')` is not supported syntax. this just merges `branch1` into your current checked out branch. I think we should fail this command with invalid argument or make it so it actually merges those two branches.

```
mysql> call dolt_checkout('main');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.00 sec)

mysql> call dolt_merge('branch1', 'branch2');
+--------------+-----------+
| fast_forward | conflicts |
+--------------+-----------+
|            1 |         0 |
+--------------+-----------+
1 row in set (0.02 sec)

mysql> select active_branch();
+-----------------+
| active_branch() |
+-----------------+
| main            |
+-----------------+
1 row in set (0.00 sec)

mysql> select * from dolt_status;
Empty set (0.00 sec)

mysql> select * from t as of branch1;
+------+------+------+
| pk   | c1   | c2   |
+------+------+------+
|    2 |    2 |    2 |
+------+------+------+
1 row in set (0.01 sec)

mysql> select * from t;
+------+------+------+
| pk   | c1   | c2   |
+------+------+------+
|    2 |    2 |    2 |
+------+------+------+
1 row in set (0.01 sec)
```

Does this seem like the problem you are seeing?

**Comment by timsehn** [comment] 2023-04-13 18:51
These aren't really stored procedures. They are just accessed using the `CALL` parameter. We definitely support variable number of arguments.

My choice would be to fail if we don't recognize or can't use what is passed in.

**Comment by lmy1218** [comment] 2023-04-14 01:46
The problem can be perfectly reproduced from my side. 

mysql> select active_branch();
+-----------------+
| active_branch() |
+-----------------+
| main            |
+-----------------+
1 row in set (0.01 sec)

mysql> call dolt_merge('dev_1001', 'dev');
Error 1105: cannot merge with uncommitted changes
mysql> select * from dolt_status;
mysql> select * from dolt_status as of 'dev';
mysql> select * from dolt_status as of 'dev_1001';
mysql> call dolt_checkout('dev');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)

mysql> call dolt_merge('dev_1001', 'dev');
+--------------+-----------+
| fast_forward | conflicts |
+--------------+-----------+
| 0            | 0         |
+--------------+-----------+
1 row in set (0.03 sec)

mysql>

**Comment by timsehn** [comment] 2023-04-14 16:39
Just to be clear `call dolt_merge('dev_1001', 'dev');` should fail. Right now, it merges `dev_1001` into your current checked out branch which in the above case is `main`. The second argument `dev` is ignored. 

The first bug we intend to fix is to make that fail with something like `dev argument not recognized`. @nicktobey is actively working on that. 

The second issue is, in Git, that merge would merge both `dev_1001` and `dev` into main. Dolt doesn't support chained merges. You can only merge two branches at once. 

The third issues is there is an option in Git merge called `[--into-name <branch>]` which we don't support in Dolt yet. We're not sure if you're expecting the chained merge behavior or if you are expecting `call dolt_merge('dev_1001', 'dev');` to merge `dev` into `dev_1001`. If you are expecting `call dolt_merge('dev_1001', 'dev');` to merge `dev` into `dev_1001` that would need to be of the form `call dolt_merge('into-name', 'dev_1001', 'dev');` which we also don't support.

I hope this explains to you what is going on.

**Comment by timsehn** [comment] 2023-04-17 21:21
This command should now fail. I'm going to resolve this because that merge call will no longer be ambiguous.

**Comment by nicktobey** [comment] 2023-04-18 00:03
Reverted, pending updating some of the bats tests.

**Comment by nicktobey** [comment] 2023-04-19 16:54
Re-fixed with https://github.com/dolthub/dolt/pull/5762

**Closed by nicktobey** 2023-04-19 16:54 UTC
Labels: bug, merge, customer-issue
