### ISSUE TITLE
 [no conn] no binlog connection to source, attempting to establish one {}

### ISSUE THREAD

**Issue by xiaogoujava** [dolthub/dolt#6817] opened 2023-10-16 07:27 UTC
step1:  CHANGE REPLICATION SOURCE TO SOURCE_HOST XXXX。
Query OK, 0 rows affected (1 min 39.10 sec)
Then,  step2:   START REPLICA;
But Keep coming back，DEBUG [no conn] no binlog connection to source, attempting to establish one {}。
please Help me figure it out。
@zachmu @andy-wm-arthur @fulghum @reltuk @coffeegoddd

**Comment by fulghum** [comment] 2023-10-16 17:06
Hey @xiaogoujava, thanks for opening an issue. We're happy to help debug this MySQL replication connection establishment issue... 

First, just in case you didn't find it already, we have some helpful documentation in [a MySQL to Dolt replication guide on our documentation site](https://docs.dolthub.com/guides/binlog-replication). 

On the MySQL source host, can you verify that you have checked these configuration parameters? You should see that `binglog_format` is `ROW` and `enforce_gtid_consistency` as well as `gtid_mode` are both set to `ON` when you run this query:
```sql
SHOW VARIABLES WHERE Variable_Name LIKE '%gtid_mode' OR Variable_Name LIKE '%enforce_gtid_consistency' OR Variable_Name LIKE '%binlog_format' OR Variable_Name LIKE 'server_id';
```

Next, when you start your `dolt sql-server` for the Dolt replica, you can add the parameter `--loglevel DEBUG` to get additional logging output. Keep an eye out for any warnings or errors in the logs that might be relevant. You should see some connection attempts logged. If you don't see anything there, you can also turn the logging up higher, to `TRACE`, but try with `DEBUG` first, since that should be enough and `TRACE` can sometimes be too much detail.

Finally, if you run `SHOW REPLICA STATUS \G` on the replica you should see some more information and hopefully any error messages about why the connection wasn't able to be established. 

Give those suggestions a try and let us know if they turn up any more clues. If you have more details to share about your MySQL and Dolt setup, that would be helpful to share, too.

**Comment by xiaogoujava** [comment] 2023-10-17 02:53
Hey @fulghum 。thanks for answering the question。
step1, On the MySQL source,I can see,

```
+--------------------------+------------+
| Variable_name            | Value      |
+--------------------------+------------+
| binlog_format            | ROW        |
| enforce_gtid_consistency | ON         |
| gtid_mode                | ON         |
| server_id                | xxx5632413 |
+--------------------------+------------+
```

step2, CHANGE REPLICATION SOURCE TO SOURCE_HOST XXXX。On the dolt server,I can see,
```Query finished in 4 ms {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalen, query=SET @@GLOBAL.SERVER_ID=17}
2023-10-17T10:25:00+08:00 DEBUG [conn 1] Starting query {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=CHANGE REPLICATION SOURCE TO SOURCE_HOST='XXXXXX', SOURCE_USER='root', SOURCE_PASSWORD='XXXXXX',SOURCE_PORT=XXX}
2023-10-17T10:25:00+08:00 TRACE [conn 1] beginning execution {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=CHANGE REPLICATION SOURCE TO SOURCE_HOST='XXXXXX', SOURCE_USER='root', SOURCE_PASSWORD='XXXXXX',SOURCE_PORT=XXX}
2023-10-17T10:25:00+08:00 TRACE [conn 1] beginning new transaction {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=CHANGE REPLICATION SOURCE TO SOURCE_HOST='XXXXXX', SOURCE_USER='root', SOURCE_PASSWORD='XXXXXX',SOURCE_PORT=XXX}
2023-10-17T10:25:00+08:00 TRACE [conn 1] committing transaction DoltTransaction {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=CHANGE REPLICATION SOURCE TO SOURCE_HOST='XXXXXX', SOURCE_USER='root', SOURCE_PASSWORD='XXXXXX',SOURCE_PORT=XXX}
2023-10-17T10:25:00+08:00 TRACE [conn 1] returning empty result {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=CHANGE REPLICATION SOURCE TO SOURCE_HOST='XXXXXX', SOURCE_USER='root', SOURCE_PASSWORD='XXXXXX',SOURCE_PORT=XXX}
2023-10-17T10:25:00+08:00 DEBUG [conn 1] Query finished in 16 ms {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=CHANGE REPLICATION SOURCE TO SOURCE_HOST='XXXXXX', SOURCE_USER='root', SOURCE_PASSWORD=XXXXXX',SOURCE_PORT=XXX}
2023-10-17T10:26:24+08:00 DEBUG [conn 1] Starting query {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=START REPLICA}
2023-10-17T10:26:24+08:00 TRACE [conn 1] beginning execution {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalen, query=START REPLICA}
2023-10-17T10:26:24+08:00 TRACE [conn 1] beginning new transaction {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=START REPLICA}
2023-10-17T10:26:24+08:00 INFO [conn 1] starting binlog replication... {connectTime=2023-10-17T10:24:50+08:00, connectionDb=testTalent, query=START REPLICA}
2023-10-17T10:26:24+08:00 DEBUG [no conn] no binlog connection to source, attempting to establish one {}
```

step3, CHANGE REPLICATION SOURCE TO SOURCE_HOST XXXX。On the dolt server, keep printing logs,
```2023-10-17T10:26:24+08:00 DEBUG [no conn] no binlog connection to source, attempting to establish one {}
2023-10-17T10:26:24+08:00 DEBUG [no conn] no binlog connection to source, attempting to establish one {}
2023-10-17T10:26:24+08:00 DEBUG [no conn] no binlog connection to source, attempting to establish one {}
```

step4, run SHOW REPLICA STATUS \G。On the replica ,I can see,
```Replica_IO_State:
                  Source_Host: XXXXX
                  Source_User: root
                  Source_Port: XXX
                Connect_Retry: 60
              Source_Log_File: INVALID
          Read_Source_Log_Pos: 0
               Relay_Log_File: NULL
                Relay_Log_Pos: NULL
        Relay_Source_Log_File: INVALID
           Replica_IO_Running: No
          Replica_SQL_Running: No
              Replicate_Do_DB: NULL
          Replicate_Ignore_DB: NULL
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table: NULL
  Replicate_Wild_Ignore_Table: NULL
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: NULL
          Exec_Source_Log_Pos: 0
              Relay_Log_Space: NULL
              Until_Condition: None
               Until_Log_File: NULL
                Until_Log_Pos: NULL
           Source_SSL_Allowed: Ignored
           Source_SSL_CA_File: NULL
           Source_SSL_CA_Path: NULL
              Source_SSL_Cert: NULL
            Source_SSL_Cipher: NULL
          Source_SSL_CRL_File: NULL
          Source_SSL_CRL_Path: NULL
               Source_SSL_Key: NULL
Source_SSL_Verify_Server_Cert: NULL
        Seconds_Behind_Source: 0
                Last_IO_Errno: 1158
                Last_IO_Error: EOF
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids: NULL
             Source_Server_Id:
                  Source_UUID: XXX-XXX-XXX-XXXXXX
             Source_Info_File: NULL
                    SQL_Delay: 0
          SQL_Remaining_Delay: 0
    Replica_SQL_Running_State: NULL
           Source_Retry_Count: 8400
                  Source_Bind: NULL
      Last_IO_Error_Timestamp: Tue Oct 17 10:26:35 CST 2023
     Last_SQL_Error_Timestamp:
           Retrieved_Gtid_Set: XXX-XXX-XXX-XXX-XXXX:1-15
            Executed_Gtid_Set: XXX-XXX-XXX-XXX-XXX:1-15
                Auto_Position: true
         Replicate_Rewrite_DB:  NULL
```
please Help me figure it out。

**Comment by fulghum** [comment] 2023-10-17 18:53
Hi @xiaogoujava, thanks for the extra information! 🙏  

From the logs you shared, I can see that Dolt is trying to connect to the MySQL source server, and the `SHOW REPLICA STATUS` output shows a little more info:
```
Last_IO_Errno: 1158
Last_IO_Error: EOF
```

Looking at the code, there's only one place where that error number comes from, but it doesn't give a lot of clues yet. It does tell us that we are getting an `EOF` from MySQL that we aren't expecting – for some reason the MySQL server is closing the connection during the middle of establishing it. 

A couple other ideas/questions...

I'm wondering if there is an issue with authenticating to the MySQL source server that's causing it to drop the connection. Could you share the MySQL version you're using (`select version()` from inside a MySQL connection)? Since the MySQL source server seems to be closing the connection, I think your best bet to find another clue is to look in the MySQL source server logs. There should be some message in there about the connection attempt and hopefully that'll give us a clue about why MySQL is closing the connection. 

Are the MySQL source server and Dolt replica server on the same host? Have you already confirmed that you can use the same user/pass to connect to the MySQL source server using the `mysql` client from the host that the Dolt replica is running on? 

You could also try disabling binlog checksums on the MySQL source server. We have tests with binlog checksums enabled, so I don't think this will fix the problem, but it might be worth a shot to try.  [binlog_checksum in MySQL](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_checksum) can be turned off with a command line flag, or by changing a global variable before you ask the replica to start replication and connect to the source server.

**Comment by timsehn** [comment] 2023-10-19 19:06
Did you ever figure this out? This seems like a bug in your replica configuration, not Dolt. We would ove to help getting you started. We offer live support via our Discord.

https://discord.gg/gqr7K4VNKe

I'm going to resolve as this is likely not a Dolt bug. Re-open if you have any new information.

**Closed by timsehn** 2023-10-19 19:06 UTC
Labels: sql server, replication, customer issue

**Comment by bpf120** [comment] 2023-10-20 17:13
Hi @xiaogoujava , we'd love to learn about your use case sometime too.  Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you are up for sharing. Thanks!
