### ISSUE TITLE
Certain JOINS Unexpectedly take a lot of time

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1520] opened 2021-04-06 23:10 UTC
```sql
SELECT DISTINCT
                    t.table_schema COLLATE 'utf8_bin' AS schema_of_table,
                    t.table_name COLLATE 'utf8_bin'   AS table_name,
                    c.column_name COLLATE 'utf8_bin'  AS column_name,
                    data_type COLLATE 'utf8_bin'      AS data_type_of_column,
                    is_nullable COLLATE 'utf8_bin'    AS is_column_nullable,
                    c.ORDINAL_POSITION
                FROM
                    information_schema.columns AS c
                JOIN
                    information_schema.tables AS t
                ON
                    t.table_schema COLLATE 'utf8_bin' = c.table_schema COLLATE 'utf8_bin' AND
                    t.table_name COLLATE 'utf8_bin' = c.table_name COLLATE 'utf8_bin'
                WHERE
                    t.table_schema NOT IN ('information_schema','performance_schema','sys','mysql','innodb','tmp') AND
                    t.table_type = 'BASE TABLE'
                     AND t.table_schema IN ('test')

                ORDER BY c.ordinal_position
 ```

There are about 20 tables in information_schema.tables

**Comment by VinaiRachakonda** [comment] 2021-04-08 22:14
The problem with this seems to be with `NOT IN` portion of the query. I set up a new repo `test` with Dolt master with no tables and ran the following

```sql
SELECT DISTINCT
    t.table_schema COLLATE 'utf8_bin' AS schema_of_table,
    c.column_name COLLATE 'utf8_bin'  AS column_name
FROM
    information_schema.columns AS c
JOIN
    information_schema.tables AS t
ON
    t.table_schema COLLATE 'utf8_bin' = c.table_schema COLLATE 'utf8_bin' AND
    t.table_name COLLATE 'utf8_bin' = c.table_name COLLATE 'utf8_bin'
WHERE
    t.table_schema NOT IN ('information_schema')
  ```
Since the repo `test` is empty this should return an empty result except it hangs. It works fine when repo `test` either has values in it or `NOT IN` becomes `IN`

**Comment by louisrigot** [comment] 2021-04-20 12:13
@VinaiRachakonda I have observed this behavior on a fairly simple JOIN query, on a database with less than 10 tables and less than 100 rows total. The query doesn't resolve (takes multiple minutes) and CPU usage for dolt spikes. Had to reset the DB, and the problem went away.

Happy to provide more info if it happens again, let me know if/how I can help.

```sql
SELECT `foo`.`id`, `foo`.`name`
FROM `foo`
         INNER JOIN `bar` ON (`foo`.`id` = `bar`.`foo_id`);
```

**Comment by timsehn** [comment] 2021-04-20 15:59
Our JOIN optimizer is not great yet. If you provide a simple repro (ie. the
schema for the above) we can usually provide a workaround that makes Dolt
do the right thing. If it's easy to fix the optimizer we will.

--Tim

**Comment by reltuk** [comment] 2021-04-20 16:03
For 10 table joins, recent improvements in Dolt should get analysis down to something pretty reasonable. From
https://www.dolthub.com/blog/2021-03-17-recent-improvements-to-join-planning/:

> Dolt went from struggling to analyze seven table joins to comfortably handling ten table joins without join order hints. By adding join order hints, the most expensive part of the search can be skipped, but the parenthesization search is still exponential and it starts slowing down noticably at around fifteen tables.

So for that particular use case, make sure you're using the latest version of Dolt.

But for much larger than that, as outlined in the blog, we've still got some work to do :).

**Comment by zachmu** [comment] 2021-08-12 18:50
Pretty sure this was caused by a bug in the join code when the secondary table was empty, fixed by https://github.com/dolthub/go-mysql-server/issues/222

In any case, the repro above now returns instantly

**Closed by zachmu** 2021-08-12 18:50 UTC
