### ISSUE TITLE
Enhancement suggestion (low priority): add an equivalent to git bundle

### ISSUE THREAD

**Issue by LaPingvino** [dolthub/dolt#6590] opened 2023-08-26 23:17 UTC
git bundle enables to package up the repository and pull from this generated file. I think it would be even nicer if the way this is being implemented involves e.g. some kind of export to a sqlite-based file format, so you can use most existing tools with the bundle.

**Comment by nicktobey** [comment] 2023-10-26 21:40
Closing as duplicate of https://github.com/dolthub/dolt/issues/6841.

**Closed by nicktobey** 2023-10-26 21:40 UTC
Labels: enhancement, build, customer issue
