### ISSUE TITLE
"Out of range for int" error

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#5630] opened 2023-03-24 23:21 UTC
query:
```sql
SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`id` = 60619803161272436420621632098471123077 LIMIT 21
```

error: `60619803161272436420621632098471123077 out of range for int`

**Comment by timsehn** [comment] 2023-03-28 23:31
Duplicate of #5642 with a worse repro

**Closed by timsehn** 2023-03-28 23:31 UTC
Labels: bug, sql, analyzer
