### ISSUE TITLE
dolt is hitting a sql lock when trying to start after shutting down

### ISSUE THREAD

**Issue by tim-oh-thee** [dolthub/dolt#6183] opened 2023-06-20 16:24 UTC
When running dolt as a docker container, the application sometimes shuts down and attempts to restart. When restarting, the application is hitting an error saying that a sql lock is on the database. The way we've handled this in the past is deleting the lock file manually. Feedback we've received from the Dolt team so far is: "dolt server should make a check to see if the process of the previous lock holder is running, and for some reason this isn't working correctly."
This is the error I'm seeing on startup: 

database locked by another sql-server; either clone the database to run a second server, or delete the '*/.dolt/sql-server.lock' if no other sql-servers are active

**Comment by zachmu** [comment] 2023-06-20 16:32
The lock file contains the PID of the locking process, so we should be able to disregard it if that PID doesn't exist.

Maybe there's a weird edge case where some users don't have access to all PIDs to make this check?

**Comment by TimoStaudinger** [comment] 2023-06-20 16:43
I wonder how this behaves if Dolt runs in a container, and the .dolt directory is mounted into the container. Different containers would mean no access to each other's PIDs, right?

**Comment by zachmu** [comment] 2023-06-20 16:48
Good question for @reltuk or @coffeegoddd, not sure how this works with containers.

**Comment by macneale4** [comment] 2023-06-20 18:35
I'm able to reproduce this if I mount a data dir, then use the --data-dir flag:

`docker run -p 3307:3306 -v $PWD:/dolt_data dolthub/dolt-sql-server:latest dolt sql-server --data-dir=/dolt_data --host=0.0.0.0 --port=3306`

The root cause of the problem is that we use the PID in the server.lock file to determine if the server is actually running. The PID in a container is always the same, so the check to determine if the PID in the lock file is a real process returns true and we end the process prematurely.

Proposed Fix: Add the process start time stamp in the lock file and use that as additional information to uniquely identify the server process. If the PID exists, but we have a different start time for it, then we'll ignore the lock.

**Comment by macneale4** [comment] 2023-06-23 17:20
Released in 1.6: https://github.com/dolthub/dolt/releases/tag/v1.6.0

Please reopen if this doesn't resolve the issue for you @tim-oh-thee !

**Closed by macneale4** 2023-06-23 17:20 UTC
Labels: bug, sql-server, docker, customer-issue
