### ISSUE TITLE
support `HEAD~` ref syntax for connection string / `USE` statements

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#3086] opened 2022-03-24 23:24 UTC
Something like this should work:

```sql
select * from `test/HEAD~`.`v1` ;
database not found: test/head~
```

Or:

```sql
use `test/HEAD~`;
```

**Comment by zachmu** [comment] 2022-08-22 17:46
@fulghum did you fix this?

**Comment by fulghum** [comment] 2022-08-22 23:48
Not yet, but it's on my radar. Should be a pretty quick change from the support we have today. I'm gunna try to get to this one this week to round out the database revision spec support.

**Comment by fulghum** [comment] 2022-08-24 20:28
Closing this one as a duplicate of https://github.com/dolthub/dolt/issues/2146

**Closed by fulghum** 2022-08-24 20:28 UTC
