### ISSUE TITLE
sql server panic when uploading table

### ISSUE THREAD

**Issue by Keimya** [dolthub/dolt#7313] opened 2024-01-12 16:18 UTC
I have been trying to upload a table through RStudio using "dbWriteTable". I run the server in my terminal where the DB is running this command
dolt sql-server -H "hostname"

and connect in R with the DBI package.

This has always worked prior to today, and even earlier today, but after succeeding several times just this morning it stopped working and throws this error in my terminal:

ERRO[0062] mysql_server caught panic:
runtime error: index out of range [3] with length 3
runtime/panic.go:114 (0x438e9b)
github.com/dolthub/go-mysql-server@v0.17.1-0.20240111001243-70f6fac07500/sql/analyzer/fix_exec_indexes.go:318 (0x1c55dcf)
github.com/dolthub/go-mysql-server@v0.17.1-0.20240111001243-70f6fac07500/sql/analyzer/fix_exec_indexes.go:52 (0x1c52d91)
github.com/dolthub/go-mysql-server@v0.17.1-0.20240111001243-70f6fac07500/sql/analyzer/fix_exec_indexes.go:38 (0x1c52cc9)
github.com/dolthub/go-mysql-server@v0.17.1-0.20240111001243-70f6fac07500/sql/analyzer/batch.go:89 (0x1c4498a)
github.com/dolthub/go-mysql-server@v0.17.1-0.20240111001243-70f6fac07500/sql/analyzer/batch.go:63 (0x1c4468e)
github.com/dolthub/go-mysql-server@v0.17.1-0.20240111001243-70f6fac07500/sql/analyzer/batch.go:55 (0x1c3afe4)

In Rstudio it says "Error in .local(conn, statement, ...) : 
  could not run statement: Lost connection to server during query" probably because the server "panics" as shown above. I just installed the latest version of Dolt as I realized I was on 1.30.0. However, it's still throwing the same error

I'd appreciate any resolution or insight into why this is happening when it's previously been successful. Thank you

**Comment by fulghum** [comment] 2024-01-12 16:49
Hi @Keimya, sorry you ran into this. Thanks for reporting the problem so we can get it fixed. 

It looks like the query analyzer has a field index that is off in the `fix_exec_indexes.go` code. @max-hoffman probably has the best idea about what could be happening to cause that. 

If you're able to repro this, it would probably be helpful to see the exact SQL queries that RStudio is sending to the Dolt sql-server. One easy way to do this is to pass the `--loglevel=DEBUG` param on the command line when you start up `dolt sql-server`.

**Comment by max-hoffman** [comment] 2024-01-12 17:06
Hi @Keimya , are there any more lines in the panic's stacktrace? It would be helpful to know what interface `dbWriteTable` is using to issue writes. I am looking for the source code right now to see if I can find out myself. How to debug the issue depends a bit on how the INSERT is being constructed.

**Comment by max-hoffman** [comment] 2024-01-12 17:14
If the error is a vanilla INSERT statement, server logs with the offending INSERT statement and a `SHOW CREATE TABLE <tablename>` that helps us reproduce the schema should help us fix. If it is a different interface, we might a data sample in the the format being imported.

**Comment by Keimya** [comment] 2024-01-12 18:26
Hi Jason and Max,

The issue seems to have resolved. I re-ran the code with --loglevel=DEBUG as you suggested and I noticed in the insert statement a column was specified that does not exist in the table schema. I removed this column and the insert now works.

Thank you both so much for your quick and helpful responses. So sorry for the false alarm!

Best,
Keimya

**Comment by timsehn** [comment] 2024-01-12 18:30
It still shouldn't panic. @max-hoffman and @fulghum any ideas on how to repro?

**Comment by max-hoffman** [comment] 2024-01-12 18:49
I might need info about the INSERT and schema that panicked. We have basic error checking for this case, particularly through the INSERT path. The LOAD data and bulk table import commands are less strict, but I do not think they would log queries to debug log. My best guess right now is that there was a prepared statement INSERT whose destination schema changed in-between PREPARE and EXECUTE. We saved an INSERT AST with a bad column, deleted the column in a different connection, and then executed the INSERT.

**Comment by Keimya** [comment] 2024-01-12 19:55
[example_for_github_issue.docx](https://github.com/dolthub/dolt/files/13923391/example_for_github_issue.docx)

Hi everyone. I attached the full stacktrace here for the failed insert. The column "MODEL" was added by me for a qc step before performing the insert and I forgot to remove it. This column isn't a real column. The schema for the table only has _car_id, model, year.

From RStudio I run the following commands:
To connect to the db:
mysqlconnection = dbConnect(RMySQL::MySQL(),
                            dbname="cars/insert-data",
                            host="xxxxxx",
                            port=3306,
                            user=Sys.getenv("user"),
                            password = Sys.getenv("password")
)

query_localinfile <- "
SET GLOBAL local_infile = 1;"
dbSendStatement(mysqlconnection, query_localinfile)

dbWriteTable(mysqlconnection, value = cars_dataframe, row.names = FALSE, name = "cars", append = TRUE)

Please let me know if there is any other information I can share to help

**Comment by Keimya** [comment] 2024-01-12 20:31
My pleasure thank you all so much for your help!

**Comment by fulghum** [comment] 2024-01-13 01:06
Just a quick update that I am able to reproduce the panic thanks to the information you provided. It looks like the current code assumes the specified columns match up to the destination table, so we just need to add some validation for that and return a helpful error message if they don't match. 

We'll keep digging into this one and get the fix released early next week.

**Comment by fulghum** [comment] 2024-01-19 19:08
I got back to this one yesterday and dug in deeper... turns out we **do** already have validation for the column names in `LOAD DATA` as well as tests for that validation. Those tests weren't triggering this error because of where the invalid column was positioned in the list of column names. I'm going to try pulling that validation out and running it at an earlier point in the query analyzer's pipeline and update our tests to make sure they trigger this case.

**Comment by max-hoffman** [comment] 2024-01-23 19:13
closing re: https://github.com/dolthub/go-mysql-server/pull/2286

**Closed by max-hoffman** 2024-01-23 19:13 UTC
Labels: bug, panic, customer issue, import

**Comment by Keimya** [comment] 2024-01-24 14:46
Awesome! And anytime I'm glad running into that error worked out and you were able to find that! Thank you so much!
