### ISSUE TITLE
Binary Bug Asked To Be Submitted By Zachmu (Dolt v0.26.2)

### ISSUE THREAD

**Issue by alexis-evelyn** [dolthub/dolt#1609] opened 2021-04-28 23:05 UTC
I decided to try adding the genome database again for Covid as I heard Binary columns are supported now, however, it appears that this specific syntax currently does not work. I tested both with [this prebuilt binary](https://github.com/dolthub/dolt/releases/download/v0.26.2/dolt-darwin-amd64.tar.gz) and with the build I produced using the same commit that the v0.26.2 tag is connected to.

I pulled the files to setup the database from https://biosql.org/wiki/Downloads (specifically [this sql file](https://gist.github.com/alexis-evelyn/fe7273d669eb4319e2f88bdc3d67d719)).

It appears that Dolt currently doesn't know the keyword `BINARY` itself.

![Screen Shot 2021-04-28 at 6 52 34 PM](https://user-images.githubusercontent.com/6305346/116482753-c4a79100-a853-11eb-94de-83f5e5b69c9d.png)

**Comment by alexis-evelyn** [comment] 2021-04-28 23:57
This is the corrected copy of the SQL File I produced with the help of Zachmu. This also bypasses the index on keyless tables error by adding primary keys that span the whole table (the creation statement already had a unique keyword for the whole table too, so I already knew the data was unique). https://gist.github.com/alexis-evelyn/7f9d433360d148cdc26fd707db9f80d7

**Comment by VinaiRachakonda** [comment] 2021-05-04 15:41
I believe this is similar to #1488. We don't support the collation necessary for this type. The linked issue has some alternatves

**Comment by zachmu** [comment] 2021-08-12 00:04
This is a duplicate of #1488

**Closed by zachmu** 2021-08-12 00:04 UTC
