### ISSUE TITLE
unknown push error When pushing a branch with a 20,000 commits to DoltHub

### ISSUE THREAD

**Issue by stephenctw** [dolthub/dolt#3087] opened 2022-03-25 02:39 UTC
```
stephen@LAPTOP-163CP44A:~/playground/dolt_pos $ dolt push --set-upstream origin experiment/explorer-1
| Tree Level: 1, Percent Buffered: 0.00%, Files Created: 2, Files Uploaded: 1, Current Upload Speed: 15 kB/s
error: push failed
cause: unknown push error; Put "https://dolthub-chunks-prod.s3.us-west-2.amazonaws.com/5ae8e9b4-ba6f-446f-85d4-d8b8a64ced4a/873tnqbg3j919ahpragjd22tgt1ot6k5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<>&X-Amz-Date=20220324T162157Z&X-Amz-Expires=900&X-Amz-Security-Token=<>&X-Amz-SignedHeaders=content-length%3Bcontent-md5%3Bhost&X-Amz-Signature=<>": write tcp 192.168.112.120:33946->52.92.144.66:443: write: connection reset by peer
```

My database is around 26 GB, the push took 15+ hours and eventually returned with this error. The upload speed is weirdly slow given my home internet plan should be ~40Mbps in upload.

I tried to upload the file (8.8GB after compression) but github won't let me. Is there a safe third party platform that I can send the file to you?

**Comment by stephenctw** [comment] 2022-03-25 16:34
File's uploaded, appreciate all the help!

**Comment by druvv** [comment] 2022-03-25 22:13
@stephenctw There was an issue with our retry logic, but it's not entirely clear what the cause of the slowdown is. Is the reported upload speed always this consistently slow for you? Or does it increase and then decrease after some time?

For now, let's see if this issue occurs with the retry logic fixed. I have a suspicion that the reported upload rate is incorrect due to way retries interact with the long running statistics gatherer that reports the upload speed. #3095 fixes the retry.

**Comment by stephenctw** [comment] 2022-03-26 01:44
The speed started with a higher number(I don't remember the exact value), then it dropped down to 15kb in a few minutes.

**Comment by timsehn** [comment] 2022-03-26 15:37
I think our plan here is for you to try pushing with the new version. We think the retry logic being broken could have messed it up. 

We'll let you know when it's merged. Are you comfortable building from the tip of master (https://docs.dolthub.com/introduction/installation/source)? Or should we also let you know when it goes out in a release?

**Comment by stephenctw** [comment] 2022-03-27 03:04
Sure I can try building from source.

**Comment by timsehn** [comment] 2022-03-27 15:00
OK. It's not merged yet. It's still being reviewed. If you're intrepid, you can build from the branch listed in the PR :-)

**Comment by timsehn** [comment] 2022-08-30 23:57
Assume this is resolved.

**Closed by timsehn** 2022-08-30 23:57 UTC
Labels: bug
