### ISSUE TITLE
command `dolt pull` returns 1 when it should return 0

### ISSUE THREAD

**Issue by sunapi386** [dolthub/dolt#5079] opened 2023-01-01 21:49 UTC
dolt version 0.51.14 on ubuntu 20.04
```
  $ dolt pull
up to date
[1]$ 
```
This seems to be functioning correctly because it says "up to date" and `git log` shows new changes, but  `dolt pull` shouldn't return 1 and print to stderr. For comparison, `git pull` returns 0 and prints to stdout. 

As a result, python's implementation of pull is broken. 
```
import doltcli as dolt
dolt_db = dolt.Dolt(folderpath)
dolt_db.pull() # fails by throwing exception
```
```
----> 1 dolt_db.pull()

File ~/workspace/project/py3venv/lib/python3.11/site-packages/doltcli/dolt.py:931, in Dolt.pull(self, remote, **kwargs)
    925 def pull(self, remote: str = "origin", **kwargs):
    926     """
    927     Pull the latest changes from the specified remote.
    928     :param remote:
    929     :return:
    930     """
--> 931     self.execute(["pull", remote], **kwargs)

File ~/workspace/project/py3venv/lib/python3.11/site-packages/doltcli/dolt.py:332, in Dolt.execute(self, args, print_output, stdout_to_file, error)
    330         output = repr(e)
    331 else:
--> 332     output = _execute(args, self.repo_dir, outfile=stdout_to_file)
    334 print_output = print_output or self._print_output
    335 if print_output:

File ~/workspace/project/py3venv/lib/python3.11/site-packages/doltcli/dolt.py:85, in _execute(args, cwd, outfile)
     83 if exitcode != 0:
     84     logger.error(err)
---> 85     raise DoltException(str_args, out, err, exitcode)
     87 if outfile:
     88     return outfile

DoltException: ('pull origin', '', 'up to date\n', 1)

```

**Comment by timsehn** [comment] 2023-01-02 00:28
Thanks for the report. We will get to this soon.

**Comment by fulghum** [comment] 2023-01-05 17:39
Very good feedback @sunapi386. Thanks for taking the time to report this. 

@stephkyou – this would be a good one for you to look at.

**Comment by stephkyou** [comment] 2023-01-17 21:57
Hi @sunapi386, I tried to reproduce the issue you noticed and couldn't seem to. Here are the steps I took:
1. `dolt clone onefact/paylesshealth`
2. `cd paylesshealth`
3. `dolt pull`
4. `echo $?` to check status of the `dolt pull`

I'm seeing `Everything up-to-date.` in stdout and a `0` status code being returned. I've also checked that there is nothing in stderr, and I've tried checking out v0.51.14 of dolt and repeating the same steps above. Could you provide more information on how I might reproduce the error? You could also try checking that you are using the latest version of dolt as this issue may have been fixed since v0.51.14.

Thanks!

**Comment by sunapi386** [comment] 2023-01-17 22:05
Thanks, I've just reproduced it.
```bash
paylesshealth$ dolt pull
up to date
paylesshealth$ echo $?
1
paylesshealth$ dolt version
dolt version 0.51.14
database storage format: NEW ( __DOLT__ )
paylesshealth$ 
```

Additionally this is my environment.
```bash
# diag info
paylesshealth$ which dolt
/usr/local/bin/dolt
paylesshealth$ ll /usr/local/bin/dolt
-rwxr-xr-x 1 root root 71565782 Jan  1 13:02 /usr/local/bin/dolt*
paylesshealth$ md5sum /usr/local/bin/dolt
b50a2776cc064addadc1d87caa3254b9  /usr/local/bin/dolt
paylesshealth$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

**Comment by stephkyou** [comment] 2023-01-24 22:27
Hi @sunapi386, thanks for the patience while I debugged this issue. It looks like you're getting an error status code here because you don't have your configs set up. You can do that with `dolt config --global --add user.name "YOUR NAME"` and `dolt config --global --add user.email YOU@DOMAIN.COM`. I've also just drafted a fix that should allow users to `dolt pull` even without configs set up since that's the behavior we ultimately want. Please let me know if you're having trouble with anything.

**Comment by sunapi386** [comment] 2023-01-24 22:41
I confirm this was the problem. I added these configs and no longer see the error. Thanks @stephkyou!

**Comment by stephkyou** [comment] 2023-01-24 22:47
Great! I'll close out this issue once my fix is merged. Thanks for pointing us to this bug!

**Closed** 2023-01-24 23:58 UTC
Labels: bug, cli
