### ISSUE TITLE
Can't add multiple foreign keys in `CREATE TABLE`

### ISSUE THREAD

**Issue by theme1256** [dolthub/dolt#7384] opened 2024-01-22 15:18 UTC
When I try to execute a `CREATE TABLE`-query with multiple foreign keys, that reference the same table, it fails with: "1105 - a foreign key with the name `4k50m025` already exists".

If I remove one of the foreign keys from the create query and run it as an alter table-query it works just fine.

This fails, but not always:
```sql
CREATE TABLE `formstatus` (
`StatusID`  int(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (`StatusID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
AUTO_INCREMENT=1

;
CREATE TABLE `formstatusflow` (
`FlowID`  int(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
`FromStatusID`  int(11) UNSIGNED NOT NULL ,
`ToStatusID`  int(11) UNSIGNED NOT NULL ,
PRIMARY KEY (`FlowID`),
FOREIGN KEY (`FromStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`ToStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE,
INDEX `Statusflow.ToStatusID` (`ToStatusID`) USING BTREE ,
INDEX `StatusFlow.FromStatusID` (`FromStatusID`) USING BTREE 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
AUTO_INCREMENT=1

;
```

I tried to create a PoC, but in doing so I wasn't able to reproduce the error.  
I have the same query open twice in Navicat. One of them fails, the other works.  
One thing is for sure: The query always fails, with the same message, when my java application executes it.

For now I'm bypassing this by manually setting the contraint name.

**Comment by theme1256** [comment] 2024-01-22 15:40
This one also fails, with keyname 'a5uc72kg'.
```sql
CREATE TABLE `usergroupsubgroup` (
`ID`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
`GroupID`  int(10) UNSIGNED NOT NULL ,
`SubGroupID`  int(11) UNSIGNED NOT NULL ,
PRIMARY KEY (`ID`),
FOREIGN KEY (`GroupID`) REFERENCES `usergroup` (`GroupID`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`SubGroupID`) REFERENCES `usergroup` (`GroupID`) ON DELETE CASCADE ON UPDATE CASCADE,
INDEX `usergroupsubgroup.GroupID` (`GroupID`) USING BTREE ,
INDEX `usergroupsubgroup.SubGroupID` (`SubGroupID`) USING BTREE 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
AUTO_INCREMENT=1

;
```

**Comment by timsehn** [comment] 2024-01-22 16:31
Good find. We'll get this fixed today. Not sure what's going on.

**Comment by fulghum** [comment] 2024-01-22 21:35
Thanks for reporting this one @theme1256. I've started to dig in, but haven't gotten a repro yet. I'm going to look at our FK constraint name generation code next and see if that gives me any ideas on reproducing this one. 

If you have more details about the Java app that is able to consistently trigger this, that could be helpful. If possible, restarting your `dolt sql-server` with `--loglevel=DEBUG` will cause all the queries the sql-server is executing to be logged. Sharing those logged queries could provide some more clues. Sometimes libraries will issue extra statements on behalf of the application that cause problems, so looking at what queries the server logs can often be helpful.

**Comment by fulghum** [comment] 2024-01-22 23:10
I dug into the code that generates FK constraint names when they aren't explicitly specified. I don't see any obvious bugs jumping out at me yet, so I think we'll need some more info from you to figure out what's going on. 

If you're curious, [here's the code where we assign an FK's name](https://github.com/dolthub/dolt/blob/3899ddf05a8254a7d31dd1c55bd5ff0a0b4b577b/go/libraries/doltcore/doltdb/foreign_key_coll.go#L333) when it isn't specified. The `key.HashOf()` method uses several fields from the FK definition to generate a hash that should generally be unique. Notably, the two FKs in your query are on different columns, and that column name (as well as a column ID/tag) is used in the unique hash generation. So far, I have only been able to trigger the "duplicate constraint name" error when I change the two FK definitions to be on the same column. 

The hash isn't perfect of course – there's a small chance that two FK definitions could hash to the same value. However... the hash should be deterministic though, so I can't explain why the query would sometimes work and sometimes not work – if the FK definition is the same, then it should generate the same hash each time and either work consistently or fail consistently. 

There are a few things that might uncover a clue for us to figure out what you're hitting: 
- sql-server logs with `--loglevel=DEBUG`. This will log the exact queries being run, and may show us that some library is silently changing a query or running extra queries. 
- more info on your Java application that can reliably reproduce this. I'm happy to set up a Java repro case if you can share more details such as how you're connecting to Dolt, what library/version you're using, etc. 
- more info on your environment. such as... what os/architecture are you seeing this one?  what version of Dolt are you running?

Let us know more of those details if you can, and we'll be happy to keep digging in.

**Comment by theme1256** [comment] 2024-01-23 12:46
I just tried running it with `--loglevel=DEBUG` and `--loglevel=TRACE`, but all that gives me is just the query and the warning, nothing useful.

I got this, which is the exact same as the original, without the linebreaks.
```sql
CREATE TABLE `formstatusflow` ( `StatusflowID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT , `SagID` int(11) UNSIGNED NOT NULL , `FromStatusID` int(11) UNSIGNED NOT NULL , `ToStatusID` int(11) UNSIGNED NOT NULL , `UUID` char(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL , `InSync` tinyint(1) NOT NULL DEFAULT 1 , `Timestamp` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP , PRIMARY KEY (`StatusflowID`), FOREIGN KEY (`FromStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`ToStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE, INDEX `Statusflow.ToStatusID` (`ToStatusID`) USING BTREE , INDEX `StatusFlow.FromStatusID` (`FromStatusID`) USING BTREE ) ENGINE=InnoDB DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci AUTO_INCREMENT=1 
```

It's a plain Java 8 webapp running on Tomcat 8.5.98, using the MariaDB-java-client 2.7.11.

I was able to reproduce the error on AMI2023 and Windows, both running Dolt 1.32.0.

**Comment by fulghum** [comment] 2024-01-23 17:47
Thank you for trying out the debug logs @theme1256! Sorry it didn't turn up any more clues. Still nice to rule out anything odd happening there though. 

I'll try this out with the MariaDB-java-client version you mentioned today and keep digging around.

**Comment by timsehn** [comment] 2024-01-23 22:22
I tried in my shell using `dolt sql` and can't reproduce the error. This one is tricky.
```
$ mkdir test_foreign_keys
$ cd test_foreign_keys 
$ ls
$ dolt init
Successfully initialized dolt data repository.
$ dolt sql -q 'CREATE TABLE `formstatus` (
`StatusID`  int(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (`StatusID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
AUTO_INCREMENT=1'
$ dolt sql -q "show tables";
+-----------------------------+
| Tables_in_test_foreign_keys |
+-----------------------------+
| formstatus                  |
+-----------------------------+

$ dolt sql -q "show create table formstatus";
+------------+------------------------------------------------------------------+
| Table      | Create Table                                                     |
+------------+------------------------------------------------------------------+
| formstatus | CREATE TABLE `formstatus` (                                      |
|            |   `StatusID` int unsigned NOT NULL AUTO_INCREMENT,               |
|            |   PRIMARY KEY (`StatusID`)                                       |
|            | ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci |
+------------+------------------------------------------------------------------+

$ dolt sql -q 'CREATE TABLE `formstatusflow` (
`FlowID`  int(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
`FromStatusID`  int(11) UNSIGNED NOT NULL ,
`ToStatusID`  int(11) UNSIGNED NOT NULL ,
PRIMARY KEY (`FlowID`),
FOREIGN KEY (`FromStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`ToStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE,
INDEX `Statusflow.ToStatusID` (`ToStatusID`) USING BTREE ,
INDEX `StatusFlow.FromStatusID` (`FromStatusID`) USING BTREE
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
AUTO_INCREMENT=1

;'
$ dolt sql -q "show create table formstatusflow";
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Table          | Create Table                                                                                                                   |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| formstatusflow | CREATE TABLE `formstatusflow` (                                                                                                |
|                |   `FlowID` int unsigned NOT NULL AUTO_INCREMENT,                                                                               |
|                |   `FromStatusID` int unsigned NOT NULL,                                                                                        |
|                |   `ToStatusID` int unsigned NOT NULL,                                                                                          |
|                |   PRIMARY KEY (`FlowID`),                                                                                                      |
|                |   KEY `StatusFlow.FromStatusID` (`FromStatusID`),                                                                              |
|                |   KEY `Statusflow.ToStatusID` (`ToStatusID`),                                                                                  |
|                |   CONSTRAINT `2gvsc9ma` FOREIGN KEY (`FromStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE, |
|                |   CONSTRAINT `hlu7k4r4` FOREIGN KEY (`ToStatusID`) REFERENCES `formstatus` (`StatusID`) ON DELETE CASCADE ON UPDATE CASCADE    |
|                | ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci                                                               |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by timsehn** [comment] 2024-01-23 22:28
I'll try on my Windows box in Powershell when I get home.

Do you have any other tables already created? A schema only dump of your db may be helpful.

**Comment by fulghum** [comment] 2024-01-23 23:13
I created a small repro project using the MariaDB connector library (version 2.7.11). I haven't been able to reproduce the issue with this project on my Mac yet, nor on an Ubuntu docker container. I also had a coworker with a Windows box try, but he wasn't able to repro either. 

Could you try cloning this project and seeing if it reproduces the issue for you on your box? 
https://github.com/fulghum/DoltFKCollisionRepro/tree/main

I put instructions for starting the Dolt server on a specific port and with a database in the readme, so hopefully those are easy to follow. 

If that doesn't reproduce the issue, then there may be something else in the environment, or in the database that is causing a problem. For example, foreign key names need to be unique across the whole database, so it's possible another FK has generated the same hash, although that wouldn't explain why you could add the FK with an `ALTER` statement instead of the `CREATE TABLE` statement. 

If you're able to share a mysql dump of the full database schema with me (you can DM me, `jasonfulghum`, on the Dolt Discord if you'd like to share it privately).

**Comment by theme1256** [comment] 2024-01-24 09:52
@fulghum I'll send you the sql-file I'm using to generate the database.

It's properbly not a java or lib problem, because when I execute the sql-file from Navicat16 against a fresh database, it still fails.  
It always generates the same key, it's always "4k50m025" for the table "formstatusflow".

**Comment by samsamm777** [comment] 2024-01-24 14:11
+1 Im having the same issue.

```
CREATE TABLE IF NOT EXISTS `asset_media_object_to_media_object` (
                                                                    `asset_media_object_id` INT(11) NOT NULL,
                                                                    `media_object_id` INT(11) NOT NULL,
                                                                    PRIMARY KEY (`asset_media_object_id`, `media_object_id`),

                                                                    FOREIGN KEY (`asset_media_object_id`)
                                                                        REFERENCES asset_media_object(`id`)
                                                                        ON DELETE CASCADE,

                                                                    FOREIGN KEY (`media_object_id`)
                                                                        REFERENCES media_object(`id`)
                                                                        ON DELETE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8 COLLATE utf8_general_ci;
```

**Comment by fulghum** [comment] 2024-01-24 18:27
Thank you for sharing the full schema @theme1256! I've got a reliable repro now and just got it hooked up under the debugger to dig in and see what's going on. 

@samsamm777 – thanks for letting us know you're affected by this, too. Now that we've got a repro, we should be able to make some quick progress on fixing this. I'll keep this ticket updated as we figure it out.

**Comment by bpf120** [comment] 2024-01-24 19:06
Thanks again @samsamm777  for letting us know. We'd love to know about your Dolt use case too. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.

**Comment by fulghum** [comment] 2024-01-24 19:32
Quick update... I found the problem – because this is happening in a sql dump file import where `FOREIGN_KEY_CHECKS` is disabled, the representation of the data for the source column is slightly different. That source column is "unresolved", which just means we haven't fully connected all the FK details yet. We store this in a separate field in the FK struct, and although that separate field is still used in the hash computation that generates the name, there was a swallowed error that was hiding an incorrect API call to put the bytes into a buffer for computing the hash. 

That explains why we weren't able to repro this more easily, and needed to be in a dump file, since those almost always set `FOREIGN_KEY_CHECKS` to disabled. It also explains why you were able to go back later and alter the table to add the foreign keys without a problem. 

Big thanks for helping us find this and for all the back and forth to help narrow in on the repro case. I've got a prototype fix that doesn't trigger the error anymore. I'll get that cleaned up, work on some tests, and then I should be able to get a fix released later today for you all.

**Comment by fulghum** [comment] 2024-01-25 02:23
The fix for this issue has been released in [Dolt 1.32.3](https://github.com/dolthub/dolt/releases/tag/v1.32.3).

@theme1256 and @samsamm777 – thank you for taking the time to report this one and helping with the repro. 🙏 Let us know anything else we can do to help you build with Dolt!

**Closed by fulghum** 2024-01-25 02:23 UTC
Labels: bug, sql, customer issue, correctness

**Comment by theme1256** [comment] 2024-01-25 11:27
Thank you for, yet another, fast bug-squashing.

Just validated that it is working on my end.

**Comment by samsamm777** [comment] 2024-01-26 12:37
Amazing! will give this a try today and see if its resolved.

**Comment by samsamm777** [comment] 2024-02-02 10:53
@fulghum Looks like this isn't fixed for me. Im still seeing the same issue. I upgraded to 1.32.6. Getting the same error with the same table as above.

**Comment by fulghum** [comment] 2024-02-02 17:42
Hey @samsamm777, sorry you're still having problems with this. I'm not able to reproduce the failure yet with the `create table` statement you shared. I disabled `@@foreign_key_checks`, which is what was required to trigger the error that we fixed for this issue, but your `create table` statements gets executed correctly without triggering any errors. Did you see this error while importing a SQL dump file as well? If you can share that dump file, or another reliable repro, then we should be able to figure out the problem quickly. Feel free to private message me on Discord (`jasonfulghum`) if that's easier for you.

**Comment by samsamm777** [comment] 2024-02-06 10:22
> Hey @samsamm777, sorry you're still having problems with this. I'm not able to reproduce the failure yet with the `create table` statement you shared. I disabled `@@foreign_key_checks`, which is what was required to trigger the error that we fixed for this issue, but your `create table` statements gets executed correctly without triggering any errors. Did you see this error while importing a SQL dump file as well? If you can share that dump file, or another reliable repro, then we should be able to figure out the problem quickly. Feel free to private message me on Discord (`jasonfulghum`) if that's easier for you.

Thanks, let me figure out a minimal repro, and ill ping you a message on Discord.
