### ISSUE TITLE
C++ connector library does not see null JSON field as null

### ISSUE THREAD

**Issue by evyalyy** [dolthub/dolt#2625] opened 2022-01-15 17:27 UTC
if JSON field is null (in terms of database), mysql c++ client library considers it a non-null field with a value of "null" (sql::ResultSet::isNull method returns false). `dolt sql` works fine.
I'm using this legacy jdbc api https://dev.mysql.com/doc/dev/connector-cpp/8.0/jdbc_ref.html

**Comment by reltuk** [comment] 2022-01-19 18:41
Thank you for the report.

Can you provide steps to reproduce here? Locally, the following seems to work as expected:

```sql
> CREATE TABLE json_test (id INT PRIMARY KEY, j JSON);
> INSERT INTO json_test VALUES (1, null), (2, '{"a": true}'), (3, "\"wat\"");
```
And then with sql-server up on that dolt repository.

```cpp
#include <iostream>
#include <memory>
#include "mysql_driver.h"
#include "cppconn/statement.h"

int main(int argc, char **argv) {
  std::string user = argv[1];
  std::string port = argv[2];
  std::string db   = argv[3];

  sql::mysql::MySQL_Driver *driver = sql::mysql::get_mysql_driver_instance();

  std::unique_ptr<sql::Connection> con(driver->connect("tcp://127.0.0.1:" + port, user, ""));
  con->setSchema(db);

  std::unique_ptr<sql::Statement> stmt(con->createStatement());
  std::unique_ptr<sql::ResultSet> res(stmt->executeQuery("select id, j from json_test"));

  while (res->next()) {
    int id = res->getInt(1);
    bool j_is_null = res->isNull(2);
    std::cout << id << ": " << j_is_null << std::endl;
  }

  return 0;
}
```

Prints:

```
1: 1
2: 0
3: 0
```

The behavior is the same run against a MySQL server.

Tested on macOS.
* dolt 0.35.5
* mysql-connector-cpp 8.0.22; jdbc repo @ the specified commit – 8cff1bacc2343e95eea206e99428341f160d91a

**Comment by evyalyy** [comment] 2022-01-19 20:24
I think you should do this insert
```
insert into json_test (id) values (4);
```

**Comment by evyalyy** [comment] 2022-01-19 21:07
Maybe there is an issue in my code, which migrates from postgres to dolt

**Comment by timsehn** [comment] 2022-03-15 16:05
Should we resolve this? We could not repro.

**Comment by fulghum** [comment] 2022-04-25 22:55
Resolving since this one has been open a while without a repro. Please feel free to reopen if this is still an issue and we'll be happy to debug through a repro case.

**Closed by fulghum** 2022-04-25 22:55 UTC
