### ISSUE TITLE
`UPDATE counters SET value = value + 1 WHERE key = 'foo';` should be concurrency-safe

### ISSUE THREAD

**Issue by sixwaaaay** [dolthub/dolt#7148] opened 2023-12-12 06:34 UTC
When concurrently executing `UPDATE counters SET value = value + 1 WHERE key = 'foo';` statements, updates to the data were lost.

This statement is concurrency-safe in both MySQL and PostgreSQL.

In dolt, data was lost at both the repeatable read and read-committed transaction isolation levels.

After one attempt to concurrently execute this statement 13,860 times, the success rate is as follows:

 

> 99% - ✓ 13853 / ✗ 7

However, the value of the final table record was 3326, and a large number of updates were lost.

------------

dolt version:

version 1.25.0

server log:
```
2023-12-12T14:24:07+08:00 INFO [conn 20] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 21] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 22] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 23] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 24] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 25] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 26] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 27] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:27+08:00 INFO [conn 28] NewConnection {DisableClientMultiStatements=false}
2023-12-12T14:25:40+08:00 WARN [conn 24] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
2023-12-12T14:25:43+08:00 WARN [conn 26] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
2023-12-12T14:25:43+08:00 WARN [conn 27] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
2023-12-12T14:25:50+08:00 WARN [conn 25] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
2023-12-12T14:25:53+08:00 WARN [conn 23] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
2023-12-12T14:25:54+08:00 WARN [conn 25] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
2023-12-12T14:25:57+08:00 WARN [conn 27] error running query {connectTime=2023-12-12T14:25:27+08:00, connectionDb=comments, error=serialization failure: this transaction conflicts with a committed transaction from another client, try restarting transaction.}
```

**Comment by timsehn** [comment] 2023-12-12 16:43
It does seem to me that we should be failing ~10,500 updates here, not 7 as reported.

**Comment by timsehn** [comment] 2023-12-12 16:57
The nuance I was missing here that @macneale4 pointed out to me on our internal chat is if two concurrent threads update `value` to the same value, in Dolt that is not a conflict and thus, the transaction succeeds. That is what you are sing. In 10,500 cases, the second transaction "merged" saw the same value as was there, and succeeded.

This is expected behavior in Dolt. It may not be desirable from a user perspective and we do want to add syntax to make Dolt transaction behave like MySQL or Postgres if that is the behavior a user wants. But it's a feature request.

**Comment by timsehn** [comment] 2023-12-12 19:11
So, we have a variable `dolt_allow_commit_conflicts` that can be set to 0 to make those types of transactions fail instead of succeed. This still won't replicate MySQL's behavior but it would be less confusing in this case and your application could retry them.

**Comment by timsehn** [comment] 2023-12-12 20:06
I'm going to write a blog about this explaining the behavior because it's a place we are intentionally different than MySQL and your counter example is an especially salient way of explaining the difference.

**Comment by timsehn** [comment] 2023-12-12 22:56
> So, we have a variable `dolt_allow_commit_conflicts` that can be set to 0 to make those types of transactions fail instead of succeed. This still won't replicate MySQL's behavior but it would be less confusing in this case and your application could retry them.

Apparently, this is not what this variable does. My bad. I am going to delete the original comment because it is confusing.

**Comment by timsehn** [comment] 2023-12-14 19:07
This is the blog explaining what is going on here:

https://www.dolthub.com/blog/2023-12-14-concurrent-transaction-example/

This will be fixed when we implement row-level locking. I'm going to resolve this as that is a big feature. It will likely land in the first half of next year.

**Closed by timsehn** 2023-12-14 19:07 UTC
Labels: enhancement, concurrency, good repro, customer issue, correctness
