### ISSUE TITLE
Respect UNIQUE constraint in CREATE TABLE statements

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#866] opened 2020-09-09 15:17 UTC
Silently dropped at the moment. Unique constraints are only respected via CREATE UNIQUE INDEX.

```
CREATE TABLE(
.....
some_field UNIQUE,
......
);
```

**Comment by Hydrocharged** [comment] 2020-10-27 23:22
Duplicate of https://github.com/dolthub/dolt/issues/961

**Closed by Hydrocharged** 2020-10-27 23:22 UTC
