### ISSUE TITLE
dolt_diff table performance

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1668] opened 2021-05-04 21:16 UTC
Repro: Clone the Hospital Price Transparency Repo -> https://www.dolthub.com/repositories/dolthub/hospital-price-transparency

Run:

```bash
hospital_price_transparency> SELECT to_commit from dolt_diff_prices order by to_commit_date desc limit 1;
timeout # output
```

**Comment by zachmu** [comment] 2021-08-12 21:11
Any full table scan of the diff table for a table with many rows and a deep edit history is going to be very bad right now.  The problem is that the `order by` means you have to examine every row in that table, and there are very many of them.

We could fix this with an index on the `to_commit_date` column and related columns. Since these are system tables we would need to define these indexes ourselves, rather than rely on customers to add them as necessary. That's a discussion we'll have to have later on.

**Comment by timsehn** [comment] 2022-08-03 21:59
Resolving this as it's a known issue as a full scan of every root.

**Closed by timsehn** 2022-08-03 21:59 UTC
Labels: performance
