### ISSUE TITLE
Dolt performance comparison to postgres and mysql 

### ISSUE THREAD

**Issue by riccardolorenzon** [dolthub/dolt#6536] opened 2023-08-18 10:17 UTC
I'm running a migration script that map objects from json files to sql statements running. 
These statements are then executed using hibernate and hikari as part of an integration test in a Micronaut application, the dbms used in the test was run using docker, all containers run with the same default CPU and memory, CPU is the one of the host machine(Apple M1 Pro), memory reserved is ~ 2GiB, the container running the dolt sql server never went above ~40% of CPU and memory usage during the migration.

I collected the hibernate stats  related to the performance with which the statements are run, the performance using dolt seems to be worse of a factor of 26: 

### Dolt 
docker container `dolthub/dolt-sql-server:latest` _no configurations specified_
```
Session Metrics {
    3360584 nanoseconds spent acquiring 1 JDBC connections;
    70500 nanoseconds spent releasing 1 JDBC connections;
    640493065 nanoseconds spent preparing 21238 JDBC statements;
    **265238251341 nanoseconds spent executing 21238 JDBC statements; -> 265.23 secs**
    0 nanoseconds spent executing 0 JDBC batches; 
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    267447755375 nanoseconds spent executing 1 flushes (flushing a total of 8680 entities and 9365 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}
```
### Postgres
docker container `postgres:latest`

 Session Metrics {
    1234459 nanoseconds spent acquiring 1 JDBC connections;
    28750 nanoseconds spent releasing 1 JDBC connections;
    29524904 nanoseconds spent preparing 21238 JDBC statements;
    **9003947583 nanoseconds spent executing 21238 JDBC statements; -> ~ 9 secs**
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    9803555084 nanoseconds spent executing 1 flushes (flushing a total of 8680 entities and 9365 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}

### Mysql
docker container `mysql:latest` 

Session Metrics {
    1621750 nanoseconds spent acquiring 1 JDBC connections;
    27084 nanoseconds spent releasing 1 JDBC connections;
    427769459 nanoseconds spent preparing 21238 JDBC statements;
    **10115899259 nanoseconds spent executing 21238 JDBC statements; -> 10 secs**
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    11399842875 nanoseconds spent executing 1 flushes (flushing a total of 8680 entities and 9365 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}

### H2 
in memory database 
Session Metrics {
    334958 nanoseconds spent acquiring 1 JDBC connections;
    29250 nanoseconds spent releasing 1 JDBC connections;
    31661047 nanoseconds spent preparing 21238 JDBC statements;
    **359971058 nanoseconds spent executing 21238 JDBC statements; -> ~ 0.35 secs**
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    1176050042 nanoseconds spent executing 1 flushes (flushing a total of 8680 entities and 9365 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}

Is there any specific optimisation configuration i'm missing to improve the performance of dolt? I can provide a reproducible scenario with an anonymised sql dump but was wondering if these numbers make sense to you and if i was missing something obvious first.

**Comment by timsehn** [comment] 2023-08-18 16:00
Thanks for the detailed performance comparison. I suspect this has something to do with our JSON path. 

Can you provide the schema of the table you are inserting into and one of the insert queries. The column names and specific data can be omitted, We just need a rough shape of the data. You can get the SQL statemts by running Dolt with `--loglvel=debug` and then inspecting the output of the sql-server process.

**Comment by riccardolorenzon** [comment] 2023-08-21 10:12
hi! i'll attach to this thread the mysql dump file and a log of all queries(anonymised) run during the migration using dolt. 
[dump.sql.zip](https://github.com/dolthub/dolt/files/12394639/dump.sql.zip)
[_logs.txt.zip](https://github.com/dolthub/dolt/files/12394958/_logs.txt.zip)

For this scenario i ran the migration for one specific unit, and it took around ~14 secs, the time increases linearly with the number of units, that are 30.

**Comment by timsehn** [comment] 2023-08-21 18:01
Thanks. I'm digging into this now.

**Comment by timsehn** [comment] 2023-08-21 18:14
So, you do not have any blob types in your schema so that is not the issue :-)

We'll have to dig deeper to see exactly why we are so much slower than MySQL.

You can speed up Dolt a couple ways:

1. Turning Foreign key checks off and then on at the end of the import. `SET FOREIGN_KEY_CHECKS=0;`
2. Batching up the inserts into larger inserts. So `insert into table values (),(),(),()` instead of a single insert per value.

I'm not sure if you need a workaround for the slow performance or you need this to work as is. So, we'll continue to debug the slow inserts on our side. It is worrying that insert performance degrades linearly with the amount of data inserted. That seems foreign key related.

**Comment by riccardolorenzon** [comment] 2023-08-22 09:54
I'm going to give a try with batch insert, disabling the foreign key constraint check didn't improve the performance significantly.

**Comment by timsehn** [comment] 2023-08-22 16:36
This is odd to me. We should dig in further here. We don't expect 20X performance difference on repeated inserts.

**Comment by nicktobey** [comment] 2023-08-22 21:21
Hi Riccardo! I'm going to help you get to the bottom of your performance issues.

I'm currently able to reproduce the issue locally using the schema you provided. I will keep you updated with the results of the my investigation.

**Comment by riccardolorenzon** [comment] 2023-08-22 21:35
hi NIck! I was trying to add the insert queries in batches, got an improvement in terms of number of statements(as expected), but still no performance improvement:
```
dolt: batched size: 50 - 
11000 nanoseconds spent acquiring 1 JDBC connections;
    119292 nanoseconds spent releasing 1 JDBC connections;
    1297161374 nanoseconds spent preparing 9102 JDBC statements;
    **0 nanoseconds spent executing 0 JDBC statements;**
    **317162634204 nanoseconds spent executing 9273 JDBC batches;**
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    320977168625 nanoseconds spent executing 1 flushes (flushing a total of 8680 entities and 9365 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}
```

**Comment by nicktobey** [comment] 2023-08-22 21:57
So it seems like running all the insert queries as a single transaction (that is, starting with a `START TRANSACTION` statement and ending with a `COMMIT` statement speeds up the queries by an order of magnitude. 

Without this, each insert has to do a lot of finalization work that involves re-chunking several levels of the storage layer. Big batch operations like this should typically be done as a single transaction to reduce this work (and to make it easier to roll back if something happens in the middle of the operation.)

**Comment by riccardolorenzon** [comment] 2023-08-23 11:55
I confirm we are already running the commands in a single transaction, so that does not seem to solve the problem.

**Comment by riccardolorenzon** [comment] 2023-08-23 14:25
@nicktobey 

It took me more than expected to check how the transaction is handled by looking at the logs, apparently MYSQL doesn't require the transaction to be declared explicitly using `START TRANSACTION;` if `autocommit` is `off`, from what i understood. 

If you check the logs i sent, you will see, on line 667, that before the `insert` statements start, `autocommit` is disabled: 
```2023-08-21T09:43:47Z DEBUG [conn 3] Query finished in 1 ms {connectTime=2023-08-21T09:43:45Z, connectionDb=test, query=SET autocommit=0}```
Right after the last insert, the transaction is committed, line 5133:
```
2023-08-21T09:44:06Z DEBUG [conn 3] Starting query {connectTime=2023-08-21T09:43:45Z, connectionDb=test, query=commit}

2023-08-21T09:44:06Z DEBUG [conn 3] Query finished in 440 ms {connectTime=2023-08-21T09:43:45Z, connectionDb=test, query=commit}```

Based on this i can confirm we are already using a single transaction, therefore the solution you proposed doesn't solve the issue we are having.

**Comment by nicktobey** [comment] 2023-08-24 01:05
Thank you for pointing out that you're already using transaction handling.

I believe I've identified the real reason why Dolt is slower when running these queries. Currently, each time Dolt executes a SQL statement, it prints a success message to standard output. For a very simple statement, the time spent formatting the output and making the OS syscall is nontrivial. For tens of thousands of simple statements, this can add up.

I'm able to reproduce this locally with a sample script: Dolt is 8 times slower than MySQL for this query, but when I remove the logic for printing the success messages it speeds up to be only 33% slower than MySQL. This isn't a factor of 26 like you were seeing, but fixing this should go a long way toward closing the performance gap.

Unfortunately, there's no way that I can current see to suppress this behavior. Fortunately, this seems like an easy fix and can make it into our next release.

I'm curious to know why this isn't being reflected in our current benchmarks. I'll investigate.

**Comment by riccardolorenzon** [comment] 2023-08-24 07:42
hi @nicktobey, do you know when the next release will be published?

**Comment by riccardolorenzon** [comment] 2023-08-24 07:42
if a beta version is available earlier, i could use it as well.

**Comment by nicktobey** [comment] 2023-08-25 01:12
Hey Riccardo. I want to apologize. My previous message was in error. I'm still able to reproduce the slowdown, but I'm still trying to identify the exact cause.

I ran five different configurations using my reproduction of your schema and queries:
1) dolt binary running query locally: 16 seconds
1) dolt client connecting to dolt server: 38 seconds
2) dolt client connecting to mysql server: 24 seconds
3) mysql client connecting to dolt server: 17 seconds
4) mysql client connecting to mysql server: 2 seconds

Something is very wrong. It seems like both our server and client are significantly slower than their mysql counterparts for this query.

Looking at the profiles for each case, both the server and the client are spending a lot of time sleeping. I'm wondering if we're using some inefficient method of server-client communication (such as only sending/accepting a single statement at a time)... but that doesn't explain why running the dolt binary alone is also so much slower than mysql.

I suspect there might be two actual issues at play: one causing our client to behave slowly, and another slowing down the actual execution of the query. (Hence why connecting with a mysql client is approximately as fast as running the query locally.)

While I continue to investigate this, could you give me more context on how you're running dolt? I'm assuming that you're running the server in a docker container and then connecting with a standard mysql client?

**Comment by riccardolorenzon** [comment] 2023-08-25 10:07
We have a Micronaut v3.9.0 application using Kotlin as programming language, JPA as abstraction layer and Hibernate as ORM engine, we use Hikari as well for the connection pool. 
Dolt is running in a docker container, in this case i'm using [testcontainers](https://testcontainers.com/) and then the connection is done via the application using the MySql connector v8.0.32. 

One thing, we are not trying to do a massive migration of millions of records, the number are quite little(about thousands), therefore the concern about the overall performance issue.

**Comment by nicktobey** [comment] 2023-08-29 22:13
Hi Riccardo. I want to thank you for your patience.

You're absolutely right that given the small size of your transaction, the performance issue here is unexpected and undesired. After some more investigation and discussion, we now have a pretty good idea why this is happening, and we have some suggestions that I believe will mitigate the issue.

It seems that Dolt currently has a performance issue that manifests when a script has a large number of INSERT statements with poor locality. Essentially, the engine has to do some amount of cleanup logic after each INSERT  statement. This cleanup is minimal as long as INSERTS that touch the same part of the database are grouped together in the script, but gets more expensive as the INSERTS become more "random".

This cleanup logic is important for preserving history independence, which is an important property that Dolt maintains that MySQL doesn't. However, the performance cost in this case is clearly unacceptable and we're exploring options to improve it. 

In the meantime, the best way to work around this issue is to improve the locality of your script.

There are multiple ways you can do this:

1. Group INSERTS by table.

Based on the log, it looks like you convert each record into a series of INSERTS on all of your tables. These INSERTS all get executed before you process the next record. Instead, you should consider reordering the statements in your script so that the tables are written to one at a time.

2. Batch inserted rows into fewer statements.

This was Tim's suggestion earlier in the discussion: instead of executing a single INSERT statement for each row you want to insert, consider adding multiple rows per statement. This allows Dolt to more efficiently do post-processing logic after each statement.

3. Sort INSERTS in a table by primary key.

Adding rows to the end of a table requires less cleanup logic than inserting into the middle of a table. Thus, pre-sorting the data may speed up the execution time.

4. Add primary keys to tables without primary keys.

When a table does not have a primary key, dolt creates one by hashing the columns of each record. Thus, inserts into a table without a primary key are extremely likely to have poor locality, since the row's position in the table is effectively random. These hashes also increase the size of the record and decrease the number of records that can fit in a single block in the database, which makes inserting into these tables more expensive. If you add a primary key to each of your tables, you can also sort the INSERTS as specified in suggestion 3.

I recommend giving all of these a try, but especially suggestions 1 and 2. In my local tests, just doing those two sped up my queries by a factor of 10.

I'm sorry that you had to deal with this performance issue. Ideally, we want using Dolt as a drop-in replacement for MySQL to be as seamless and painless as possible. A script that works in MySQL should have comparable performance in Dolt without needing these sorts of tweaks. I'll be creating a separate issue to track the work on fixing this, since I know it's a bad user experience.

Let me know if you're still having performance issues after incorporating these changes and I'll be happy to help further.

**Comment by timsehn** [comment] 2023-09-08 19:23
Resolving this in favor of the specific #6603

**Closed by timsehn** 2023-09-08 19:23 UTC
Labels: performance, customer issue
