### ISSUE TITLE
Feature Request:  Version Notice

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4788] opened 2022-11-14 23:41 UTC
A notice when issuing a dolt command that you're using an outdated version.

**Comment by fulghum** [comment] 2022-11-15 17:15
Hey @ericmock, thanks for the feature request. This would be a great hook to have in the CLI to let customers know if the version they're using is out of date or has some issue worth noting.

**Comment by timsehn** [comment] 2022-12-01 00:26
Duplicate of #3417.

**Closed by timsehn** 2022-12-01 00:26 UTC
Labels: feature, cli
