### ISSUE TITLE
Joins against columns with case insensitive collations sometimes compare the join condition as if they were case sensitive.

### ISSUE THREAD

**Issue by reltuk** [dolthub/dolt#7080] opened 2023-12-01 00:07 UTC
Given:

```sql
CREATE TABLE names (id INT PRIMARY KEY, name VARCHAR(128) COLLATE utf8mb4_0900_ai_ci NOT NULL);
INSERT INTO names VALUES (1, 'aaron'), (2, 'Aaron'), (3, 'AARON');
CREATE TABLE ref (name VARCHAR(128));
INSERT INTO ref VALUES ('aaron');
```

MySQL gives:

```
mysql> select * from names where name = 'aaron';
+----+-------+
| id | name  |
+----+-------+
|  1 | aaron |
|  2 | Aaron |
|  3 | AARON |
+----+-------+
3 rows in set (0.01 sec)

mysql> select * from names where name in (select name from ref);
+----+-------+
| id | name  |
+----+-------+
|  1 | aaron |
|  2 | Aaron |
|  3 | AARON |
+----+-------+
3 rows in set (0.00 sec)
```

and Dolt gives:

```
hashjoinci> select * from names where name = 'aaron';
+----+-------+
| id | name  |
+----+-------+
| 1  | aaron |
| 2  | Aaron |
| 3  | AARON |
+----+-------+
3 rows in set (0.00 sec)

hashjoinci> select * from names where name in (select name from ref);
+----+-------+
| id | name  |
+----+-------+
| 1  | aaron |
+----+-------+
1 row in set (0.00 sec)
```

In this case Dolt is choosing a SemiJoin against the subquery results, but I've also seen this happen with a different schema on a HashJoin.

**Comment by max-hoffman** [comment] 2023-12-01 17:44
Maybe related:
```
left, right, compareType, err = c.castLeftAndRight(left, right)
// left = utf8mb4_0900_ai_ci
// right = utf8mb4_0900_bin
// compareType = utf8mb4_0900_bin
```

`castLeftAndRight` just returns `types.LongText` as a default, it doesn't try to merge collations.

**Comment by nicktobey** [comment] 2023-12-04 21:08
So I think the actual issue here is that Dolt and MySQL have different server defaults for collation.

In MySQL:

```sql
> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_0900_ai_ci   |
+--------------------------+----------------------+
```

Thus, the table `ref` in the example has a case-insensitve collation.

But in Dolt:

```
> SELECT @@character_set_database, @@collation_database;
+----------------------------------+------------------------------+
| @@SESSION.character_set_database | @@SESSION.collation_database |
+----------------------------------+------------------------------+
| utf8mb4                          | utf8mb4_0900_bin             |
+----------------------------------+------------------------------+
```

Thus, the table `ref` in the example has a binary collation.

[According to the MySQL Spec](https://dev.mysql.com/doc/refman/8.0/en/charset-collation-coercibility.html):

> For an operation with operands from the same character set but that mix a _bin collation and a _ci or _cs collation, the _bin collation is used. 

So given the different default collation, Dolt has the correct behavior here by using a binary collation for the join.

**Comment by nicktobey** [comment] 2023-12-04 21:11
[According to the Dolt documentation, this different is deliberate, because it's both more efficient and consistent with earlier versions of Dolt:](https://docs.dolthub.com/sql-reference/sql-support/miscellaneous#collations-and-character-sets)

> This default was chosen as it has the fastest implementation, and also from a legacy perspective, as before proper collation support was added, it was the only real collation that we supported. This differs from a standard MySQL instance, which defaults to utf8mb4_0900_ai_ci (a case-insensitive collation).

**Comment by nicktobey** [comment] 2023-12-05 23:52
If a user needs to use case-insensitive collation for the comparison, that can be specified in the expression itself:

Dolt:
```
> select * from names where (name collate utf8mb4_0900_ai_ci in (select name from ref));
+----+-------+
| id | name  |
+----+-------+
| 1  | aaron |
| 2  | Aaron |
| 3  | AARON |
+----+-------+
```

**Comment by nicktobey** [comment] 2023-12-20 01:05
I'm going to close this as not a bug. If we want to change the default collation (and I don't think we do), that should be a separate issue.

**Closed by nicktobey** 2023-12-20 01:05 UTC
Labels: bug, analyzer, correctness
