### ISSUE TITLE
Socket not closing

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#3752] opened 2022-07-05 15:00 UTC
Using Knex to connect to a Dolt database, it seems there is an unclosed socket that lingers even after calling knex.destroy(), which results in the node process being left open and requiring the script to manually be killed (ctrl-C or process.exit() after knex.destroy() in the script).

This does not occur when connecting to a mysql db. In that case, the process exits after knex.destroy() is called.

Consider the following test script:

```
import wtfnode from 'wtfnode'; // to debug what's holding the process open
import Knex from 'knex';

// Dolt
const config = {
  client: 'mysql2',
  connection: {
    database: 'information_schema',
    user: '...',
    password: '...',
    host: 'localhost',
    port: 3307,
  },
};

// MySQL
// const config = {
//   client: 'mysql2',
//   connection: {
//     database: 'information_schema',
//     user: '...',
//     password: '...',
//     host: 'localhost', // default mysql port 3306
//   },
// };

(async function main() {
  const knex = Knex(config);
  try {
    await knex.raw('select 1;');
    await knex.destroy();
    setTimeout(() => {
      wtfnode.dump();
    }, 3000);
  } catch (err) {
    console.log('error:', err);
  }
})();

```

Running this using the mysql db config, the connection is destroyed after knex.destroy(), and the wtfnode dump shows no sockets open:
```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
  - fd 0 (tty)
- Timers:
  - (3000 ~ 3 s) (anonymous)
```
The process closes after the dump.

Running using the dolt db config, the wtfnode dump shows there is still an open socket:
```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
  - fd 0 (tty)
- Sockets:
  - 127.0.0.1:59372 -> 127.0.0.1:3307
- Timers:
  - (3000 ~ 3 s) (anonymous)
```
Thus the node process hangs open and the script does not exit unless manually killed, or if the dolt server is stopped.

However, the dolt server logs do show that a connection was created and then closed:
```
2022-07-05T10:49:30-04:00 INFO [conn 4] NewConnection {DisableClientMultiStatements=false}
2022-07-05T10:49:30-04:00 INFO [conn 4] ConnectionClosed {}
```

Is it possible Dolt is reporting the connection closed but not entirely cleaning up resources related to the connection?

**Comment by fulghum** [comment] 2022-07-05 15:37
Hey @dphil, thanks for reporting this and providing the excellent debugging info. We'll dig into this today and let you know what we find.

**Comment by dphil** [comment] 2022-07-05 15:41
Thanks. I tried both older and newer versions of node (12 and 18) and knex (0.19 and 2.1) both with the same result.

**Comment by VinaiRachakonda** [comment] 2022-07-05 21:01
@dphil I'd love to know what type of machine you are running this program on. I am unable to reproduce either the hanging behavior or the open socket with my 2019 Mac. It's running  `npm: '8.13.1'` and `node: '16.15.0',`

**Comment by VinaiRachakonda** [comment] 2022-07-05 23:37
I would appreciate the dolt version as well

**Comment by dphil** [comment] 2022-07-06 14:37
Here are the most recent versions of the relevant software/packages I've reproduced the issue with:

dolt: 0.40.15
node: 18.0.0
knex: 2.1.0
mysql2: 2.3.3

OS Ubuntu 20.04.4 LTS, 64-bit.

Also, just to clarify that so far this occurs consistently for me, 100% of the time.

**Comment by reltuk** [comment] 2022-07-06 16:12
@dphil Thank for you the detailed information.

I can confirm that we can reproduce with a `dolt sql-server` process running on Ubuntu.

**Comment by VinaiRachakonda** [comment] 2022-07-06 18:11
I can reproduce it as well on my ubuntu vm.

**Comment by VinaiRachakonda** [comment] 2022-07-07 02:29
We've come up with the fix. We'll get some tests in and put out a release tomorrow. Thank you!

**Comment by VinaiRachakonda** [comment] 2022-07-08 06:04
Just wanted to check in. I wanted to do another quick deep in Knex's mechanics before I merge and release. Thank you for your patience!

**Comment by VinaiRachakonda** [comment] 2022-07-08 20:17
Hi, we've merged the fix and are getting out a release today

**Closed** 2022-07-08 20:17 UTC
Labels: bug

**Comment by VinaiRachakonda** [comment] 2022-07-09 01:34
We just release a new version of Dolt. Thank you!
