### ISSUE TITLE
Support `information_schema.columns AS OF` in parser

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6502] opened 2023-08-12 18:40 UTC
The columns table is important for allowing schema inspection via the SQL engine. We currently use private internal GMS interfaces for gathering table or column schemas because of the column's table's lack of flexibility. Coupling the infoschema.columns AS OF with a helper to parse sql.Schema and schema.Schema types only with the information schema would be great.

**Comment by timsehn** [comment] 2023-09-25 22:21
Dupe of #5663

**Closed by timsehn** 2023-09-25 22:21 UTC
Labels: sql, analyzer
