### ISSUE TITLE
Official Docker hub image?

### ISSUE THREAD

**Issue by bring-shrubbery** [dolthub/dolt#4463] opened 2022-10-05 07:29 UTC
## The problem

I would like to be able to run Dolt locally via docker-compose, so that I don't need to mess around with shell scripts too much.

I know that I can already run dolt using docker compose, as described [here](https://docs.dolthub.com/introduction/installation/docker#docker-compose-sql-server), but it requires you to also create a Docker image for building it.

## Ideal solution

Would be great to have an official pre-built image at https://hub.docker.com, so I can just have a docker-compose file that looks something like this when testing:

```yml
services:
  db:
    image: dolthub/dolt
    ports:
      - '3306:3306'
```

**Comment by timsehn** [comment] 2022-10-05 14:43
This is a dupe of #1897. I'm going to push the team to actually do this.

**Closed** 2022-10-05 14:44 UTC

**Comment by fulghum** [comment] 2022-10-05 16:54
Thanks for poking on this one @bring-shrubbery. This is overdue! We'll get the official DockerFile published to our repo today and start work integrating DockerHub publishing into our release pipeline. Feel free to follow along on the main tracking issue Tim mentioned, or come by [our Discord](https://discord.com/invite/RFwfYpu) and hang out.

**Comment by bring-shrubbery** [comment] 2022-10-09 11:05
@fulghum Thanks, and sorry for not noticing the original issue, I swear I checked :D
