### ISSUE TITLE
Make Dolt work with Fivetran through its MySQL connector

### ISSUE THREAD

**Issue by Eronarn** [dolthub/dolt#4007] opened 2022-08-03 22:14 UTC
As part of a Dolt->Snowflake data export, I wanted to use a SaaS connector tool to avoid needing to write my own ETL. Since Dolt aims to be MySQL compatible, I chose each tool's MySQL connector.

Setup:
- Self-hosted EC2 Dolt database: `dolt version 0.40.18`
- Letsencrypt certificate served by Dolt
- SSH jumpbox to connect
- User/pass auth, granted `SELECT` access to `<app database>.*` and `mysql.*`

# Airbyte

Timeout error of some kind. Unclear if this is even Dolt related.

```
Could not connect with provided configuration. Error: HikariPool-1 - Connection is not available, request timed out after 60002ms.
```

# Stitchdata

Successfully connects through tunnel, but hits fatal error on `Error: %s Unknown system variable 'innodb_lock_wait_timeout'`

```
2022-08-03 22:08:53,635Z   main - INFO Running tap-hp-mysql version 1.3.2 and target-stitch-avro version 0.2.2
2022-08-03 22:08:54,808Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2022-08-03 22:08:54,820Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2022-08-03 22:08:54,830Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
<SSH TUNNEL CONFIG SNIPPED>
2022-08-03 22:08:55,896Z   main - INFO Successfully connected to tunnel
2022-08-03 22:08:57,381Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [16] at offset None
2022-08-03 22:08:57,382Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-hp-mysql --config /tmp/tap_discover_config.json --discover
2022-08-03 22:09:00,127Z    tap - WARNING: error-handler already refers to: #'clojure.core/error-handler in namespace: com.stitchdata.target-stitch-avro.flush-pipeline, being replaced by: #'com.stitchdata.target-stitch-avro.flush-pipeline/error-handler
2022-08-03 22:09:00,742Z    tap - INFO  [main] tap-hp-mysql.main - Started nrepl server at /127.0.0.1:45453
2022-08-03 22:09:00,764Z    tap - INFO  [main] tap-hp-mysql.core - Starting discovery mode
2022-08-03 22:09:01,253Z    tap - INFO  [main] tap-hp-mysql.config - Connecting to MySQL version 5.7.9-Vitess
2022-08-03 22:09:01,455Z    tap - WARN  [main] tap-hp-mysql.config - Encountered error checking server params. Error: %s Unknown system variable 'innodb_lock_wait_timeout'
2022-08-03 22:09:01,465Z    tap - FATAL [main] tap-hp-mysql.main - Fatal Error Occurred - 
2022-08-03 22:09:01,482Z    tap - ERROR [main] #error {
2022-08-03 22:09:01,482Z    tap -  :cause nil
2022-08-03 22:09:01,482Z    tap -  :via
2022-08-03 22:09:01,482Z    tap -  [{:type java.lang.NullPointerException
2022-08-03 22:09:01,483Z    tap -    :message nil
2022-08-03 22:09:01,483Z    tap -    :at [clojure.string$lower_case invokeStatic string.clj 217]}]
2022-08-03 22:09:01,483Z    tap -  :trace
2022-08-03 22:09:01,483Z    tap -  [[clojure.string$lower_case invokeStatic string.clj 217]
2022-08-03 22:09:01,483Z    tap -   [clojure.string$lower_case invoke string.clj 213]
2022-08-03 22:09:01,483Z    tap -   [tap_hp_mysql.config$maybe_add_mariadb_compatibility invokeStatic config.clj 61]
2022-08-03 22:09:01,483Z    tap -   [tap_hp_mysql.config$maybe_add_mariadb_compatibility invoke config.clj 55]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.config$check_connection invokeStatic config.clj 72]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.config$check_connection invoke config.clj 65]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.config$__GT_conn_map_STAR_ invokeStatic config.clj 121]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.config$__GT_conn_map_STAR_ invoke config.clj 99]
2022-08-03 22:09:01,484Z    tap -   [clojure.lang.AFn applyToHelper AFn.java 154]
2022-08-03 22:09:01,484Z    tap -   [clojure.lang.AFn applyTo AFn.java 144]
2022-08-03 22:09:01,484Z    tap -   [clojure.core$apply invokeStatic core.clj 665]
2022-08-03 22:09:01,484Z    tap -   [clojure.core$memoize$fn__6877 doInvoke core.clj 6353]
2022-08-03 22:09:01,484Z    tap -   [clojure.lang.RestFn invoke RestFn.java 408]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.discovery$build_catalog invokeStatic discovery.clj 173]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.discovery$build_catalog invoke discovery.clj 172]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.discovery$discover invokeStatic discovery.clj 181]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.discovery$discover invoke discovery.clj 179]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.core$do_discovery invokeStatic core.clj 19]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.core$do_discovery invoke core.clj 17]
2022-08-03 22:09:01,484Z    tap -   [tap_hp_mysql.main$main_impl invokeStatic main.clj 98]
2022-08-03 22:09:01,485Z    tap -   [tap_hp_mysql.main$main_impl invoke main.clj 90]
2022-08-03 22:09:01,485Z    tap -   [tap_hp_mysql.main$_main invokeStatic main.clj 147]
2022-08-03 22:09:01,485Z    tap -   [tap_hp_mysql.main$_main doInvoke main.clj 136]
2022-08-03 22:09:01,485Z    tap -   [clojure.lang.RestFn applyTo RestFn.java 137]
2022-08-03 22:09:01,485Z    tap -   [tap_hp_mysql.main main nil -1]]}
2022-08-03 22:09:01,485Z    tap - INFO  [main] com.stitchdata.target-stitch-avro.core - wait-for-target
2022-08-03 22:09:01,485Z    tap - INFO  [main] com.stitchdata.target-stitch-avro.core - flushing remaining pending requests: []
2022-08-03 22:09:01,485Z    tap - INFO  [main] tap-hp-mysql.main - Shutting down the nrepl server
2022-08-03 22:09:01,520Z   main - INFO Tap exited abnormally with status 1
2022-08-03 22:09:02,399Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [27] at offset None
2022-08-03 22:09:02,402Z   main - INFO Closed tunnel and deleted temporary keyfile
2022-08-03 22:09:02,402Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "[main] tap-hp-mysql.main - Fatal Error Occurred - ".
```

# Fivetran

```
Unable to validate database user
SELECT privilege needed on tables you wish to sync
```

Fivetran gets the farthest along, successfully connecting to the database and authing as a user. However, the error seems to be that Fivetran implicitly depends on `SHOW GRANTS` to determine what tables it should synchronize. Dolt does not seem to actually return a user's grants with this command, so Fivetran thinks the user has no table access and refuses to proceed further:

```
mysql> grant select on mysql.* to fivetran@'%';
mysql> grant select on clauses.clause to fivetran@'%';
mysql> SHOW GRANTS FOR 'fivetran'@'%';
+--------------------------------------+
| Grants for fivetran@%                |
+--------------------------------------+
| GRANT USAGE ON *.* TO `fivetran`@`%` |
+--------------------------------------+
mysql> GRANT SELECT, INSERT on clauses.clause TO fivetran@'%';
mysql> SHOW GRANTS FOR 'fivetran'@'%';
+--------------------------------------+
| Grants for fivetran@%                |
+--------------------------------------+
| GRANT USAGE ON *.* TO `fivetran`@`%` |
+--------------------------------------+
```

**Comment by fulghum** [comment] 2022-08-03 23:14
Thanks so much for capturing all this data @Eronarn! This is super helpful, and very appreciated.

Since it looks like Fivetran is the closest to working, that seems like a good place for us to start digging in. I've repro'ed the same behavior you see – granting access to a user doesn't show up in the `show grants` output. I'll ping @JCOR11599 to dig into what's going on there and get us an update.

**Comment by timsehn** [comment] 2022-08-03 23:20
The show grants issue isn already documented here https://github.com/dolthub/dolt/issues/3589

**Comment by timsehn** [comment] 2022-08-12 00:29
Can you try Fivetran again and let us know if it works with the table grants fix?

**Comment by Eronarn** [comment] 2022-08-16 00:43
I updated to `0.40.25` today to test this. The `SHOW GRANTS;` changes work as expected, thank you!

This style of issuing grants didn't work:

```
mysql> show grants for fivetran;
+----------------------------------------------------------+
| Grants for fivetran@%                                    |
+----------------------------------------------------------+
| GRANT SELECT ON *.* TO `fivetran`@``                     |
| GRANT SELECT ON `clauses`.`clause` TO `fivetran`@``      |
| GRANT SELECT ON `clauses`.`clause_type` TO `fivetran`@`` |
| GRANT SELECT ON `mysql`.* TO `fivetran`@``               |
+----------------------------------------------------------+
```

When using it, I got this error back from Fivetran:

```
{
  "event" : "connection_failure",
  "data" : {
    "actor" : "account-owners@tome.com",
    "id" : "clauses",
    "testName" : "Validating certificate",
    "message" : "com.fivetran.lambda.Retrier$RetrierException: The action failed after 1 attempt(s), the failures were:\n1) java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLException: User not found 'fivetran'\n"
  },
  "created" : "2022-08-16T00:00:31.215Z"
}
```

It looked a bit odd to me so I deleted and recreated the user, and explicitly set `%` in the user creation and grants:

```
mysql> show grants for fivetran;
+-----------------------------------------------+
| Grants for fivetran@%                         |
+-----------------------------------------------+
| GRANT USAGE ON *.* TO `fivetran`@`%`          |
| GRANT SELECT ON `clauses`.* TO `fivetran`@`%` |
| GRANT SELECT ON `mysql`.* TO `fivetran`@`%`   |
+-----------------------------------------------+
```

That did get the test connection working. I'm not so up on MySQL, plus there's also the SSH tunnel here, so I'm not really sure what the former syntax falls back to or whether it's a bug or just my mistake :) But at least if anyone else runs across this error there'll be a search result now...

I finished setting up the connector with their "Teleport Sync" replication feature, which should be able to run against any DB (I assumed any Mysql-replication-log features simply wouldn't be supported). It ran for quite some time and created Snowflake tables with the correct schema, but ultimately inserted 0 rows.

I'm not yet sure if that's due to a Fivetran issue or a Dolt issue; but FWIW I do have Fivetran and Snowflake working properly against a Postgres database. Going to try another sync to see if that one catches any records.

**Comment by timsehn** [comment] 2022-08-16 00:51
Great. Yes that missing `%` issue we fixed today and will be in the next release. We required explicit definition of the `%` for the host field or left it empty whereas MySQL automatically populated it with `%`. Glad you worked around it.

You are correct, we don't support binlog style replication. We use Git-style push and pull for replication. (https://docs.dolthub.com/concepts/dolt/rdbms/replication)

So, when trying to export Dolt data to Snowflake using Fivetran, you got the tables created but not the data.

If the second sync also fails, run the Dolt SQL Server in debug or trace and see what queries Fivetran is trying to run. That will give us some hints as to why you're not getting any data.

**Comment by timsehn** [comment] 2022-08-16 01:37
We’ll poke through these tomorrow and see if anything is off

**Comment by timsehn** [comment] 2022-08-16 16:20
This is not a thorough analysis but some obvious missing function support is likely the cause.

We at least don't support `BIT_XOR()` or `CONV()`

Docs: https://docs.dolthub.com/sql-reference/sql-support/expressions-functions-operators#functions-and-operators
Source: https://github.com/dolthub/go-mysql-server/tree/main/sql/expression/function

We'll scope those out today. `BIT_XOR()` is definitely easy. `CONV()` may be harder.

**Comment by timsehn** [comment] 2022-08-16 16:23
I made new issues for these specific functions:

`BIT_XOR()`: https://github.com/dolthub/dolt/issues/4098
`CONV()`: https://github.com/dolthub/dolt/issues/4099

**Comment by timsehn** [comment] 2022-08-18 20:05
So `BIT_XOR()` is released and `CONV()` is in main. 

Next release, (or on a build of main if you're courageous) you should try Fivetran again. I think this time it will work. If it doesn't I'll go over the SQL logs again.

**Comment by timsehn** [comment] 2022-08-23 22:29
Latest release has `BIT_XOR()` and `CONV()` if you'd like to try again.

**Comment by timsehn** [comment] 2022-08-24 19:56
Made #4190 for Stitchdata. I'm going to rename this issue.`Make Dolt work with Fivetran`.

**Comment by timsehn** [comment] 2022-08-31 17:30
Going to assume the additional functions fixed this. Please reopen or make a new if you can't get stitchdata working with Dolt.

**Closed by timsehn** 2022-08-31 17:30 UTC
Labels: tool integrations
