### ISSUE TITLE
CRS type should be signed

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#5948] opened 2023-05-15 17:30 UTC
Hi all!, first read this https://github.com/dolthub/dolt/issues/5931

Now, I think instead of:

```
There's no spatial reference with SRID 4294967294
```

Would be great and more intuitive have the actual CRS we are using (in the example was used the 3857):

```
There's no spatial reference with SRID 3857
```

Issue updated:

Check https://github.com/dolthub/dolt/issues/5948#issuecomment-1549824844

Thx!

**Comment by JCOR11599** [comment] 2023-05-16 07:28
Looking at the `data.gpkg` you sent, it appears that the line causing the error is this
```sql
INSERT INTO `aeropuertos` (`geom` , `objectid_1`, `cod_comuna`, `categoría`, `cod_oaci`, `cod_iata`, `aerodromo`, `region`, `provincia`, `comuna`) VALUES (ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',-2) , 39, 3201, 'Aeródromo', 'SCRA', 'CNR', 'Aeródromo Chañaral', 'Región de Atacama', 'Chañaral', 'Chañaral')
```

The `4294967294` is caused by `-2` overflowing the `uint32`, I think there might be a bad SRID somewhere in the data.

You can try out the sql commands and see the errors through `dolt sql`
```shell
ogr> select ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',-2);
There's no spatial reference with SRID 4294967294
ogr> select ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',3857);
There's no spatial reference with SRID 3857
```

**Comment by latot** [comment] 2023-05-16 14:48
oks, @JCOR11599 Here is again, two different issues.

First, I renamed the issue, because the CRS is a signed type, while Dolt have it as a unsigned one, due to that, error message is so confuse.

CRS -1 means "Unknown", while -2 means "Not Initalized", I asked this on GDAL, and is more close issue to the one posted.

The other one is why ogr2ogr + Dolt is inserting data "-2"/"Not initialized", I'll open other issue for that.

Thx!

**Comment by JCOR11599** [comment] 2023-05-16 20:16
Small update here, I have PR out to report SRID errors closer to MySQL.

Additionally, I tested the double import on a MySQL server, and it works without any issue; I believe there is something with the way SRIDs are defined on columns. My current theory is that MySQL must tell ogr2ogr something about the table, so that ogr2ogr knows to populate the `-2` with the correct SRID.

Continuing to dig on this now.
Thanks again for the bug report!

**Comment by latot** [comment] 2023-05-16 20:31
Hi!, thx checking it!

I have opened this issue: https://github.com/dolthub/dolt/issues/5960

Is for decide how to handle the -1 and -2 CRS because it should not report an error, even if MySQL does.

Thx! :D

**Comment by JCOR11599** [comment] 2023-05-17 06:27
Fix for this has been merged to dolt main.

The SRIDs errors in dolt are more consistent with what MySQL does, and negative SRIDs don't overflow.

**Closed by JCOR11599** 2023-05-17 06:27 UTC
Labels: bad-error-message, customer-issue
