### ISSUE TITLE
[dolt migrate]: Incorrect datetime value

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4625] opened 2022-10-26 01:06 UTC
```
migration failed
cause: Incorrect datetime value: '%!s(int64=1376251200)'
```

is returned by private repo:
https://www.dolthub.com/repositories/dolthub/test-private-prod

**Comment by druvv** [comment] 2022-10-26 01:06
Last commit date was 9/2/2021... pretty old!

**Comment by andrew-wm-arthur** [comment] 2022-10-27 17:30
duplicate of https://github.com/dolthub/dolt/issues/4474

**Closed by andrew-wm-arthur** 2022-10-27 17:30 UTC
Labels: bug, new format (__DOLT__)
