### ISSUE TITLE
record updates are extremely slow through SQLModel/SQLAlchemy

### ISSUE THREAD

**Issue by SamDM** [dolthub/dolt#2751] opened 2022-02-04 15:39 UTC
I am using dolt through [sqlmodel](https://sqlmodel.tiangolo.com/) (version 0.0.6) on python 3.6.

The problem is that updating records through orm is extremely slow.
Below is just an example, but the phenomenon seems to be more general.

```python
cam_id = 10
pose_id = 20

batch_size = 1000
engine = create_engine("mysql+pymysql://root@localhost:3306/example_db")

with Session(engine) as session:
    # this part takes a fraction of a second
    frames = session.exec(
        select(Frame).
        where(Frame.camera_id == cam_id)
    ).all()

    # this part is slow
    for i, frame in enumerate(tqdm(frames)):
        frame.pose_id = pose_id
        session.add(frame)
        if i % batch_size == 0:
            session.commit()
```

The first few thousand frames went at a speed of around 70 updates per second.
However, after about 20K updates, this drops to roughly 11 updates per second.
If I remove the 'commit' statement, the second part also completes in a fraction of a second, but of course without any updates to the database. In conclusion, it seems like the 'commit' is the bottleneck here.

I have noticed before that table updates go slow. In fact most Dolt write operations go very slow compared to e.g. an SQLite backend.

The frames table has around 600K rows.
The database lives in my `$HOME` directory and is hosted locally.
It has the following schema, auto-generated by sqlmodel/sqlalchemy 
`dolt schema show frames`

```sql
CREATE TABLE `frames` (
  `id` int NOT NULL AUTO_INCREMENT,
  `camera_id` int NOT NULL,
  `recording_id` int NOT NULL,
  `pose_id` int,
  `index` int NOT NULL,
  `timestamp` float,
  PRIMARY KEY (`id`),
  KEY `camera_id` (`camera_id`),
  KEY `ix_frames_index` (`index`),
  KEY `pose_id` (`pose_id`),
  KEY `recording_id` (`recording_id`),
  CONSTRAINT `loqpge43` FOREIGN KEY (`recording_id`) REFERENCES `recordings` (`id`),
  CONSTRAINT `n4pfq0pq` FOREIGN KEY (`camera_id`) REFERENCES `cameras` (`id`),
  CONSTRAINT `q0ht6qj1` FOREIGN KEY (`pose_id`) REFERENCES `poses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Even stranger, this query, resulting in the same database state, completed in about 20 seconds.
(executed in the `dolt sql` shell)
```sql
example_db> UPDATE frames SET pose_id = 20 WHERE frames.camera_id = 10;
Query OK, 105360 rows affected
Rows matched: 128872  Changed: 105360  Warnings: 0
```

So, what could be causing the overhead?
I'm not expecting an answer, but any pointers to debug this would be most welcome.
If I find the bottleneck, I'd be happy to report my conclusions.

**Comment by timsehn** [comment] 2022-02-04 16:46
Thanks for the report. We know performance is a problem and we are measuring/improving it actively:

https://docs.dolthub.com/reference/sql/latency

Currently, we are 5X slower than MySQL on sysbench tests (https://docs.dolthub.com/reference/sql/latency) and about 20X slower than MySQL on TPCC (a high throughput transaction workflow). The reason for the TPCC difference is that we don't have row level locking yet.

All that said, what you're seeing seems like a bug. We would expect the SQL shell and the SQL server to give similar performance. We will dig into this today and see what we can find. Your repro is really nice.

**Comment by andrew-wm-arthur** [comment] 2022-02-04 22:03
@SamDM thanks for all the detail. 

The root of the problem is how transactions are implemented in Dolt, and how that differs from MySQL. The code example above is batching the updates in sets of 1K rows. However the `sqlmodel` ORM is still generating one update query each row batched. MySQL can handle this performantly by accumulating the changes in memory and writing them out in a single transaction. Dolt does not handle this as well and writes to disk after every `UPDATE` statement, effectively un-batching the queries. As you noted above, writing the update as a single query that touches multiple rows _does_ perform well in Dolt. 
Executing the update in raw SQL is likely the best way to make it performant at this time. From what I've read in the `sqlmodel` documentation, the ORM will not group updates as a single query.

**Comment by SamDM** [comment] 2022-02-07 08:55
@andrew-wm-arthur Thanks for the insights. This is actionable knowledge if you want to apply the same update to a lot of rows at once, as in the example above.

However, what would be the most performant way to perform a large amount of heterogeneous row updates? E.g. setting a different 'pose_id' for each row above. In that case, there is no way to do this in a single SQL statement. Would it be faster to make a json file with updated data and use e.g. `dolt table import -u` to apply the changes in batch?

**Comment by VinaiRachakonda** [comment] 2022-02-07 18:34
@SamDM It would be great to get the schemas of the other tables references in the foreign keys of `frames`. If you're also comfortable sharing the complete database that would be awesome as well!

**Comment by VinaiRachakonda** [comment] 2022-02-07 19:17
The ORM model definitions would be great as well

**Comment by timsehn** [comment] 2022-02-07 19:21
Just for context, we're going to deep dive on this because this performance degradation is worse than we expect. If you can provide us more detail, we can at least provide you an explanation of what is going on and probably patch dolt to work better in this particular case.

**Comment by timsehn** [comment] 2022-02-07 19:59
> @andrew-wm-arthur Thanks for the insights. This is actionable knowledge if you want to apply the same update to a lot of rows at once, as in the example above.
> 
> However, what would be the most performant way to perform a large amount of heterogeneous row updates? E.g. setting a different 'pose_id' for each row above. In that case, there is no way to do this in a single SQL statement. Would it be faster to make a json file with updated data and use e.g. `dolt table import -u` to apply the changes in batch?

It would definitely be faster to use `dolt table import -u`. That batches all the updates up into a single transaction.

**Comment by SamDM** [comment] 2022-02-08 18:58
@timsehn @VinaiRachakonda 

I'm really happy that you want to dig into this. I'll see if I can make a small repro without sharing any company IP that I'm not allowed to share. Just the ORM definitions and some randomly generated data will do fine.

I'm a bit busy at work right now, but I hope by next week I can share a gist to reproduce the slow update behavior.

**Comment by timsehn** [comment] 2022-02-08 19:22
We generated random data for the schema you provided and it eventually got down to 40TPS but never 7TPS. We have a hypothesis we're testing with ascending (auto_increment) keys. If you can confirm you have auto_increment keys somewhere, it would be a good hint for us.

**Comment by SamDM** [comment] 2022-02-09 11:33
Well, if you're this far already, here are the ORM definitions:

```python
import datetime
from typing import Optional, List, Tuple, Dict

import sqlalchemy as sa
from sqlmodel import SQLModel, Field, Relationship, Column, DateTime


class Frame(SQLModel, table=True):
    __tablename__ = "frames"

    id: Optional[int] = Field(default=None, primary_key=True)
    camera_id: int = Field(foreign_key="cameras.id")
    recording_id: int = Field(foreign_key="recordings.id")
    pose_id: Optional[int] = Field(foreign_key="poses.id")
    index: int = Field(index=True)
    timestamp: Optional[float]

    recording: "Recording" = Relationship(back_populates="frames")
    camera: "Camera" = Relationship(back_populates="frames")
    pose: Optional["Pose"] = Relationship(back_populates="frames")


class Camera(SQLModel, table=True):
    __tablename__ = "cameras"

    id: Optional[int] = Field(default=None, primary_key=True)
    intrinsic_id: Optional[int] = Field(foreign_key='camera_intrinsics.id')
    serial: str
    width: int
    height: int
    channels: int

    frames: List[Frame] = Relationship(back_populates="camera")
    intrinsics: Optional["CameraIntrinsics"] = Relationship(
        back_populates="cameras"
    )


class Recording(SQLModel, table=True):
    __tablename__ = "recordings"
    __table_args__ = (sa.UniqueConstraint("use_case", "name"),)

    id: Optional[int] = Field(default=None, primary_key=True)
    use_case: str
    name: str
    start_time: datetime.datetime = Field(
        sa_column=Column(DateTime(timezone=True))
    )

    frames: List[Frame] = Relationship(back_populates="recording")



class CameraIntrinsics(SQLModel, table=True):
    __tablename__ = "camera_intrinsics"

    id: Optional[int] = Field(default=None, primary_key=True)

    # focal length
    fx: float
    fy: float
    # principal point
    cx: float
    cy: float
    # Brown-Conrady lens-distortion parameters (OpenCV notation)
    k1: float = Field(default=0)
    k2: float = Field(default=0)
    p1: float = Field(default=0)
    p2: float = Field(default=0)
    k3: float = Field(default=0)
    k4: float = Field(default=0)
    k5: float = Field(default=0)
    k6: float = Field(default=0)
    s1: float = Field(default=0)
    s2: float = Field(default=0)
    s3: float = Field(default=0)
    s4: float = Field(default=0)
    tx: float = Field(default=0)
    ty: float = Field(default=0)

    cameras: List[Camera] = Relationship(back_populates="intrinsics")


class Pose(SQLModel, table=True):
    __tablename__ = "poses"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    # world -> pose rotation vector in Rodrigues notation, see:
    # https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation#Rotation_vector
    rx: float
    ry: float
    rz: float
    # world -> pose translation
    tx: float
    ty: float
    tz: float

    frames: List[Frame] = Relationship(back_populates="pose")
```

All the `id` fields are auto-incrementing primary keys.
This code results in the automatic creation of the following tables:

```sql
CREATE TABLE `frames` (
  `id` int NOT NULL AUTO_INCREMENT,
  `camera_id` int NOT NULL,
  `recording_id` int NOT NULL,
  `pose_id` int,
  `index` int NOT NULL,
  `timestamp` float,
  PRIMARY KEY (`id`),
  KEY `camera_id` (`camera_id`),
  KEY `ix_frames_index` (`index`),
  KEY `pose_id` (`pose_id`),
  KEY `recording_id` (`recording_id`),
  CONSTRAINT `loqpge43` FOREIGN KEY (`recording_id`) REFERENCES `recordings` (`id`),
  CONSTRAINT `n4pfq0pq` FOREIGN KEY (`camera_id`) REFERENCES `cameras` (`id`),
  CONSTRAINT `q0ht6qj1` FOREIGN KEY (`pose_id`) REFERENCES `poses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cameras` (
  `id` int NOT NULL AUTO_INCREMENT,
  `intrinsic_id` int,
  `serial` varchar(255) NOT NULL,
  `width` int NOT NULL,
  `height` int NOT NULL,
  `channels` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `intrinsic_id` (`intrinsic_id`),
  CONSTRAINT `gr6rethv` FOREIGN KEY (`intrinsic_id`) REFERENCES `camera_intrinsics` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `recordings` (
  `start_time` datetime,
  `id` int NOT NULL AUTO_INCREMENT,
  `use_case` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `use_casename` (`use_case`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `camera_intrinsics` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fx` float NOT NULL,
  `fy` float NOT NULL,
  `cx` float NOT NULL,
  `cy` float NOT NULL,
  `k1` float,
  `k2` float,
  `p1` float,
  `p2` float,
  `k3` float,
  `k4` float,
  `k5` float,
  `k6` float,
  `s1` float,
  `s2` float,
  `s3` float,
  `s4` float,
  `tx` float,
  `ty` float,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `poses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `rx` float NOT NULL,
  `ry` float NOT NULL,
  `rz` float NOT NULL,
  `tx` float NOT NULL,
  `ty` float NOT NULL,
  `tz` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

```

I only have a few cameras, recordings, intrinsics and poses. I do have around 500K frames though. And this will likely grow to several millions.

@timsehn regarding the auto_increment. I did notice that inserting new records through the ORM is super slow if you ask the database to auto-generate new keys (I took care of not flushing, or not requiring the new keys for other records in other tables, in the same database session/commit). If on the other hand I explicitly insert the primary key (by just updating a counter in python and passing that value to the ORM), the updates go way faster.The difference was at least a factor 50 or so. 

I am surprised though that my frame updates above have anything to do with auto_incrementing keys. Because all I did was make new connections between frames and poses, but all frames and poses were already in the database, so no new keys need to be created. Of course the pose_id field is a foreign key and therefore indexed, which makes updates a bit slower.

**Comment by VinaiRachakonda** [comment] 2022-02-09 22:53
@SamDM After investigating the performance bug, it seems like SqlModel implicitly batches inserts when Auto Increment value is specified. When the auto increment value is unspecified, SqlModel assigns one insert per transaction. 

Dolt's transactional model is still a little new so one transaction per insert will take substantially longer. While we address this performance problem, it is best to just specify the auto increment value.

**Comment by timsehn** [comment] 2022-08-03 22:49
Resolving as we reached a natural conclusion here.

**Closed by timsehn** 2022-08-03 22:49 UTC
