### ISSUE TITLE
Windows paths not understood by `dolt add` in Powershell

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1227] opened 2021-01-19 17:56 UTC
`dolt add .\README.md` fails but `dolt add README.md` works.

Assume the same is true of `dolt checkout` and `dolt reset`.

**Comment by zachmu** [comment] 2021-08-11 18:38
Duplicate of https://github.com/dolthub/dolt/issues/1100

**Closed by zachmu** 2021-08-11 18:38 UTC
Labels: windows
