### ISSUE TITLE
Feature: auto-create branches on connect

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#5743] opened 2023-04-13 22:15 UTC
When a customer specifies a branch that doesn't exist in their connection string, Dolt should have the option to create that branch automatically, via a system variable or similar.

New branches created in this way should derive from the default branch of the DB. Branches with a slash in the name can be derived from the nearest existing ancestor branch determined by splitting the branch path. E.g. `org223/march2023/week5` should derive from `org223/march2023` if it exists, or `org223` otherwise.

**Comment by timsehn** [comment] 2023-04-14 20:19
Duplicate of #2460

**Closed by timsehn** 2023-04-14 20:19 UTC
Labels: enhancement, sql-server
