### ISSUE TITLE
natural order insert issue possibly foreign key related

### ISSUE THREAD

**Issue by bheni** [dolthub/dolt#1362] opened 2021-02-23 00:25 UTC
bheniToday at 4:09 PM
am i doing something wrong here, or is this a bug:
```sql
CREATE TABLE colors (
    id INT NOT NULL,
    color VARCHAR(32) NOT NULL,

    PRIMARY KEY (id),
    INDEX color_index(color)
);
CREATE TABLE materials (
    id INT NOT NULL,
    material VARCHAR(32) NOT NULL,
    color VARCHAR(32),

    PRIMARY KEY(id),
    FOREIGN KEY (color) REFERENCES colors(color),
    INDEX color_mat_index(color, material)
);
CREATE TABLE objects (
    id INT NOT NULL,
    name VARCHAR(64) NOT NULL,
    color VARCHAR(32),
    material VARCHAR(32),

    PRIMARY KEY(id),
    FOREIGN KEY (color,material) REFERENCES materials(color,material)
);
INSERT INTO colors VALUES (1,'red');
INSERT INTO materials VALUES (1,'steel','red');
INSERT INTO objects VALUES (1,'truck','red','steel');
```
last statement yields: 
```
test> INSERT INTO objects VALUES (1,'truck','red','steel');
foreign key violation on `objects`.`9k3ocmeh`: (6670,"steel",12609,"red")
```
oh shit
this works:
```
INSERT INTO objects (id,name,color,material) VALUES (1,'truck','red','steel');
```
HydrochargedToday at 4:12 PM
flipped the columns
pk is on (color, material)
bheniToday at 4:12 PM
pk is id
HydrochargedToday at 4:13 PM
whoops didn't mean pk, meant fk
bheniToday at 4:13 PM
what is the "natural order"
as in
if I don't specify `(id,name,color,material)`
why is it not the order I created in?
HydrochargedToday at 4:14 PM
Oh I misread this
andyaToday at 4:14 PM
looks like there's a bug?
bheniToday at 4:14 PM
I guess it's in this order:
```
test> describe objects;
+----------+-------------+------+-----+---------+-------+
| Field    | Type        | Null | Key | Default | Extra |
+----------+-------------+------+-----+---------+-------+
| id       | int         | NO   | PRI |         |       |
| name     | varchar(64) | NO   |     |         |       |
| material | varchar(32) | YES  |     |         |       |
| color    | varchar(32) | YES  | MUL |         |       |
+----------+-------------+------+-----+---------+-------+
```
but I don't know how that order is determined
HydrochargedToday at 4:15 PM
It shouldn't be, it should be in the declared order from what I can tell
This looks like a bug
bheniToday at 4:15 PM
k, i'll file it
thx
HydrochargedToday at 4:15 PM
Assign me I'll take a look later this week
Unless Andy has an idea
andyaToday at 4:15 PM
if you retry 
```sql
INSERT INTO colors VALUES (1,'red');
INSERT INTO materials VALUES (1,'steel','red');
INSERT INTO objects VALUES (1,'truck','red','steel');
```
with the order specified, does it work as expected?
bheniToday at 4:16 PM
isn't that what i did above?
the original
andyaToday at 4:16 PM
i see now, yes
so it's just a "natural ordering" problem
bheniToday at 4:17 PM
yeah looks it
not sure if it's a straight up insertion problem
or an fk check problem
HydrochargedToday at 4:18 PM
What are the tags for the tables?
andyaToday at 4:18 PM
seems like the FK checks are working, but I'd have to debug to be sure
bheniToday at 4:19 PM
works without the FKs:
```
test> CREATE TABLE colors (
   ->     id INT NOT NULL,
   ->     color VARCHAR(32) NOT NULL,
   ->
   ->     PRIMARY KEY (id),
   ->     INDEX color_index(color)
   -> );
test> CREATE TABLE materials (
   ->     id INT NOT NULL,
   ->     material VARCHAR(32) NOT NULL,
   ->     color VARCHAR(32),
   ->
   ->     PRIMARY KEY(id));
test> CREATE TABLE objects (
   ->     id INT NOT NULL,
   ->     name VARCHAR(64) NOT NULL,
   ->     color VARCHAR(32),
   ->     material VARCHAR(32),
   ->
   ->     PRIMARY KEY(id));
test> INSERT INTO colors VALUES (1,'red');
Query OK, 1 row affected
test> INSERT INTO materials VALUES (1,'steel','red');
Query OK, 1 row affected
test> INSERT INTO objects VALUES (1,'truck','red','steel');
Query OK, 1 row affected
test> SELECT * from objects;
+----+-------+-------+----------+
| id | name  | color | material |
+----+-------+-------+----------+
| 1  | truck | red   | steel    |
+----+-------+-------+----------+
```
HydrochargedToday at 4:20 PM
@bheni with it erroring, what were the the tags?
since the fk error attaches tags to it
bheniToday at 4:20 PM
unfortunately i killed it
then recreated
and now it works with the natural ordering
so it must be tag ordering issue
HydrochargedToday at 4:21 PM
that's weird
andyaToday at 4:21 PM
"tag ordering issue" sounds bad

**Comment by Hydrocharged** [comment] 2021-03-05 14:26
I cannot reproduce this at all, and nothing stands out as to why this happened. Closing for now.

**Closed by Hydrocharged** 2021-03-05 14:26 UTC
