### ISSUE TITLE
Add more features to CREATE TABLE SELECT

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#1817] opened 2021-06-14 01:30 UTC
Add table specs option to CREATE SELECT such as `CREATE TABLE tbl(pk int) as SELECT ok from othertable`

**Comment by zachmu** [comment] 2021-08-12 21:49
Duplicate of https://github.com/dolthub/dolt/issues/1478

**Closed by zachmu** 2021-08-12 21:49 UTC
