### ISSUE TITLE
DBeaver: data tables in-cell updates are not picked-up by Dolt

### ISSUE THREAD

**Issue by mtyszler** [dolthub/dolt#3957] opened 2022-07-28 15:24 UTC
When using DBeaver if you modify a table content, the changes are not picked up by dolt.

When the same change is made via SQL query, it runs fine.

**EXAMPLE**

_original status_

![image](https://user-images.githubusercontent.com/23292639/181574096-117f369d-2262-4631-808b-1faba9b9ad81.png)

_Inline change_

![image](https://user-images.githubusercontent.com/23292639/181574175-de28fec5-9c77-4ab9-945d-e7c765447424.png)

(click on `save`)

_Check_

![image](https://user-images.githubusercontent.com/23292639/181574232-f896d5cc-aa97-41db-973b-65f6fcfaceab.png)

**no changes**

_via script_

![image](https://user-images.githubusercontent.com/23292639/181574528-b36524e8-1ccc-4cd9-914c-441bc5782f3e.png)

![image](https://user-images.githubusercontent.com/23292639/181574735-35f92480-d9c0-4626-b2d4-1b970f720ec0.png)

_Check_

![image](https://user-images.githubusercontent.com/23292639/181575826-5da0cc86-8a9b-4853-85e2-cfd86a6b84cf.png)

**changed is picked by be staged**

-----------------------

**Any idea why the inline edit is ignored?**

**Comment by timsehn** [comment] 2022-07-28 21:13
We could not reproduce this. Here is the video of us trying:

https://user-images.githubusercontent.com/5376236/181638442-efb53430-159d-4987-9abf-c2ca1d6a3ee1.mp4

Looks like potentially you did not save the table?

**Comment by mtyszler** [comment] 2022-07-28 21:49
> We could not reproduce this. Here is the video of us trying:
> 
>  blonk-demo.mp4 
> Looks like potentially you did not save the table?

I did save, and could see the changes on the table after refresh, but not in the status.

I'll create a reprex tomorrow

**Comment by mtyszler** [comment] 2022-07-28 21:55
I'll send more info tomorrow @timsehn ,  but your show case seem to be different than my problem (if I understood what you did).

My case:

* take an existing table with existing content (already committed)
* modify a cell

**Comment by timsehn** [comment] 2022-07-28 21:59
From the video, that happens at the 0:50s mark. We'll keep banging at this. We're also posting updates on Discord.

**Comment by mtyszler** [comment] 2022-07-28 22:00
> From the video, that happens at the 0:50s mark. We'll keep banging at this. We're also posting updates on Discord.

Tks. I see. I'll try to do again to confirm. I'll update you tomorrow

**Comment by mtyszler** [comment] 2022-07-29 08:15
TKs @VinaiRachakonda for following it up on the related https://github.com/dolthub/dolt/issues/3959

**Comment by mtyszler** [comment] 2022-07-29 08:16
I can know confirm that the issue happens ONLY when a database is not named in the connection settings or not set as default

So you could mark this as solved, if you assume the user has to select a DB. Still would be nice to have this with less "not-so-clear" handling :)

**Comment by VinaiRachakonda** [comment] 2022-07-29 17:10
Great @mtyszler! I appreciate the follow up. Closing the issue.

**Closed by VinaiRachakonda** 2022-07-29 17:10 UTC
