### ISSUE TITLE
Branch Not Created

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolt#4777] opened 2022-11-14 19:33 UTC
`dolt checkout main && dolt pull onefact && dolt checkout -b branch_AC 2>&1`

```
Already on branch 'main'
Updating flsvjs54n9i4l98mm9v6cjgskbkiulna..s5sq76i35hlmee2kpdletj5fl60ff8uk
Already up to date.
current fast forward from a to b. a is ahead of b already
```

The branch is not created or checked out as it should be and as a user would expect it to be.

**Comment by timsehn** [comment] 2022-11-14 19:43
So I think what happened is that the dolt pull command failed. ie. exited status non-zero. The `&&` checks that the status is 0 and if it is not, fails. Thus, the branch command never executed. You can get around this by using a `;`.

Are you arguing that a `dolt pull` where your branch is locally ahead should not exit non-zero?

**Comment by timsehn** [comment] 2022-11-14 20:37
```
$ dolt commit --allow-empty -m "Test commit"
commit co6t7li43g543u9anngvkkhrd7fn17fa (HEAD -> main) 
Author: timsehn <tim@dolthub.com>
Date:  Mon Nov 14 12:33:08 -0800 2022

        Test commit

$ dolt pull                                 
Updating co6t7li43g543u9anngvkkhrd7fn17fa..tf8to5e4vmpussiq3kv13l2e2lcsvpcp
Already up to date.
current fast forward from a to b. a is ahead of b already
$ echo $?                                   
1
```

So, I think that is what is happening. 

I need more info on why you think your branch is not ahead of what you are pulling. 

Otherwise, this is intended behavior.

**Comment by ericmock** [comment] 2022-11-14 22:05
I think I figured it out.  I'd accidentally made some changes on main.  I reset things but need to do a "hard" reset.

**Comment by timsehn** [comment] 2022-11-14 22:32
Great. Resolving. Keep em coming.

**Closed by timsehn** 2022-11-14 22:32 UTC
Labels: question, cli
