### ISSUE TITLE
Aliases in UPDATE query leads to error

### ISSUE THREAD

**Issue by theetrain** [dolthub/dolt#5519] opened 2023-03-08 18:06 UTC
In MySQL, the following query runs well:

```sql
UPDATE addon_items a
LEFT JOIN base_items b
ON a.`Base Item`= b.`Base Item`
SET a.`Price`=b.`Price (Region)` * 2
WHERE a.`id`='abc';
```

Demo: https://www.db-fiddle.com/f/4gyrk8evGN6ENR2f7gNWXb/2

However in Dolt, it leads to an error:

```
sqlState: "HY000",
sqlMessage: "The target table a of the UPDATE is not updatable 
```

My workaround is to use the full table name instead of aliases:

```sql
UPDATE addon_items
LEFT JOIN base_items
ON addon_items.`Base Item`= base_items.`Base Item`
SET addon_items.`Price`=base_items.`Price (Region)` * 2
WHERE addon_items.`id`='abc';
```

Maybe relates to #5481 
Dolt version: v0.54.2

**Comment by timsehn** [comment] 2023-03-08 18:13
I think this is related to #5481 and is fixed in main. We have a release going out today. Do you want to try the tip of main?

**Comment by timsehn** [comment] 2023-03-08 18:14
@max-hoffman what do you think?

**Comment by timsehn** [comment] 2023-03-08 18:24
The tip of main throws a better error:
```
$ dolt sql < test.sql
error on line 1 for query UPDATE addon_items
LEFT JOIN base_items
ON addon_items.`Base Item`= base_items.`Base Item`
SET addon_items.`Price`=base_items.`Price (Region)` * 2
WHERE addon_items.`id`='abc': unsupported feature: error: keyless tables unsupported for UPDATE JOIN
unsupported feature: error: keyless tables unsupported for UPDATE JOIN
```

This is now a duplicate of #2134

Can you add primary keys?

Also, `text` columns in MySQL are blobs, you almost definitely want `varchar` columns, even `varchar(max)`.

**Comment by timsehn** [comment] 2023-03-08 18:27
```
$ dolt sql -q "alter table addon_items modify column id varchar(max)"
$ dolt sql -q "alter table addon_items add primary key (id)"         
$ dolt sql -q "alter table base_items modify column \`Base Item\` varchar(max)"
$ dolt sql -q "alter table base_items add primary key (\`Base Item\`)"
$ dolt sql -q "alter table addon_items modify column \`Base Item\` varchar(max)"
$ dolt sql < test.sql                                                          
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

**Comment by max-hoffman** [comment] 2023-03-08 18:28
If I edit the fiddle above to add primary keys to the tables, I get the same error as you on `v0.54.2`. That altered repro passes on dolt main.

The repro with keyless tables throws a keyless error for `unsupported feature: error: keyless tables unsupported for UPDATE JOIN` on both main and `v0.54.2`.

A bit confusing repro but I think Tim's summary about working on main is accurate.

**Comment by timsehn** [comment] 2023-03-08 18:28
The error message will be fixed in the next release.

**Closed** 2023-03-08 18:28 UTC
Labels: sql, bad-error-message
