### ISSUE TITLE
Cannot create UNIQUE index on FK fields Dolt considers it duplicate

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#959] opened 2020-10-27 03:11 UTC

**Comment by zachmu** [comment] 2020-10-27 16:39
@Hydrocharged has a fix in for this, I believe. He should close this when we do a release including it.

**Comment by Hydrocharged** [comment] 2020-10-27 23:19
This is a duplicate of https://github.com/dolthub/dolt/issues/891, which has already been fixed and merged, and is also present in the latest release.

**Closed by Hydrocharged** 2020-10-27 23:19 UTC
Labels: bug, turbine
