### ISSUE TITLE
When executing a query in SQL, the error message is unrelated to the SQL statement.

### ISSUE THREAD

**Issue by lmy1218** [dolthub/dolt#6224] opened 2023-06-25 07:05 UTC
2023-06-25T14:58:07+08:00 WARN [conn 389] error running query {connectTime=2023-06-25T14:55:55+08:00, connectionDb=gos_1041, error=error: 'AttrAdd' is not a valid value for 'bigint', query=SELECT gos_config_1041.BattleSkill.BattleSkill_1t6vo3, gos_config_1041.BattleSkill.BattleSkill_23yche, gos_config_1041.BattleSkill.BattleSkill_53poim, gos_config_1041.BattleSkill.BattleSkill_7j9k07, gos_config_1041.BattleSkill.BattleSkill_99miry, gos_config_1041.BattleSkill.BattleSkill_cmnl48, gos_config_1041.BattleSkill.BattleSkill_hw7rvf, gos_config_1041.BattleSkill.BattleSkill_kjl78u, gos_config_1041.BattleSkill.BattleSkill_m0h2yt, gos_config_1041.BattleSkill.BattleSkill_noj242, gos_config_1041.BattleSkill.BattleSkill_nvlbyb, gos_config_1041.BattleSkill.BattleSkill_qmgieb, gos_config_1041.BattleSkill.id, gos_1041.gos_config_system.created_by as createdBy, gos_1041.gos_config_system.created_time as createdTime, gos_1041.gos_config_system.updated_by as updatedBy, gos_1041.gos_config_system.updated_time as updatedTime FROM gos_config_1041.BattleSkill as of 'dev-f1' LEFT OUTER JOIN gos_1041.gos_config_system ON gos_1041.gos_config_system.config_id = gos_config_1041.BattleSkill.id WHERE ( gos_1041.gos_config_system.branch_id = '4' AND gos_1041.gos_config_system.table_id = '221') limit 0, 30}

**Comment by lmy1218** [comment] 2023-06-25 08:29
When there is a table with a string field as the primary key, such as BattleSubBuff, it will affect the queries of other normal tables and cause errors.
schema:
mysql> DESCRIBE BattleSubBuff as of 'DEV';
+----------------------+--------------+------+-----+---------+-------+
| Field                | Type         | Null | Key | Default | Extra |
+----------------------+--------------+------+-----+---------+-------+
| id                   | varchar(900) | NO   | PRI | NULL    |       |
| BattleSubBuff_zj124y | varchar(900) | YES  |     | NULL    |       |
+----------------------+--------------+------+-----+---------+-------+
2 rows in set (0.00 sec)

mysql> DESCRIBE Rss as of 'DEV';
+------------+--------------+------+-----+---------+-------+
| Field      | Type         | Null | Key | Default | Extra |
+------------+--------------+------+-----+---------+-------+
| Rss_50al80 | int          | YES  |     | NULL    |       |
| id         | bigint       | NO   | PRI | NULL    |       |
| Rss_eph4rk | varchar(900) | YES  |     | NULL    |       |
| Rss_ir4ycw | varchar(900) | YES  |     | NULL    |       |
| Rss_thnb2p | varchar(255) | YES  |     | NULL    |       |
| Rss_ixtzdz | varchar(255) | YES  |     | NULL    |       |
| Rss_kgnl35 | varchar(900) | YES  |     | NULL    |       |
| Rss_e6x3ph | varchar(900) | YES  |     | NULL    |       |
| Rss_mx2ygy | bigint       | YES  |     | NULL    |       |
| Rss_bcn54z | bigint       | YES  |     | NULL    |       |
| Rss_ulf8by | bigint       | YES  |     | NULL    |       |
+------------+--------------+------+-----+---------+-------+
11 rows in set (0.01 sec)

mysql> DESCRIBE gos_1041.gos_config_system;
+--------------+----------------------------------------+------+-----+---------+----------------+
| Field        | Type                                   | Null | Key | Default | Extra          |
+--------------+----------------------------------------+------+-----+---------+----------------+
| id           | bigint                                 | NO   | PRI | NULL    | auto_increment |
| branch_id    | bigint                                 | YES  |     | NULL    |                |
| config_id    | varchar(90) COLLATE utf8mb4_0900_ai_ci | YES  |     | NULL    |                |
| table_id     | varchar(90) COLLATE utf8mb4_0900_ai_ci | YES  |     | NULL    |                |
| created_by   | varchar(90) COLLATE utf8mb4_0900_ai_ci | YES  |     | NULL    |                |
| created_time | datetime(6)                            | YES  |     | NULL    |                |
| updated_by   | varchar(90) COLLATE utf8mb4_0900_ai_ci | YES  |     | NULL    |                |
| updated_time | datetime(6)                            | YES  |     | NULL    |                |
+--------------+----------------------------------------+------+-----+---------+----------------+
8 rows in set (0.01 sec)

**Comment by timsehn** [comment] 2023-06-26 15:06
@max-hoffman you mind seeing if you can repro. I'm nervous about the `left outer join`.

**Comment by max-hoffman** [comment] 2023-06-26 15:15
Looking now.

**Comment by bpf120** [comment] 2023-06-26 15:23
@lmy1218 Thanks for filing. We'd love to learn about your Dolt use case too. You can share here, [email me](mailto:brianF@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.

**Comment by max-hoffman** [comment] 2023-06-26 16:54
This is definitely a bad error message, we are trying to solve the global root cause in the medium term. I am having trouble reproducing your from the information given though. A left join is only going to have one join order option, `BattleSkill` x `gos_config_system`. There is only one join edge `gos_config_system.config_id = BattleSkill.id`. That only leaves a couple options of how this can be executing. And we have wheedled out most errors in join condition code between incompatible types, which is tested pretty at this point.

I am wondering if there is a schema/versioning problem, potentially a check constraint, or some bad schema merge. The info below might be helpful:
```
show create table gos_1041.gos_config_system;
show create table  gos_config_1041.BattleSkill;
show create table  gos_config_1041.BattleSkill as of 'dev-f1';

**Comment by lmy1218** [comment] 2023-06-27 01:26
After deleting and recreating the database and tables, the issue was resolved, but the root cause has not been identified yet.

**Comment by lmy1218** [comment] 2023-06-27 02:41
There is another problem that has been bothering me for a long time. Occasionally, I encounter the following error during merges, even though I have checked and found that both branches have the same table structure and do not have two commits simultaneously.
2023-06-27T10:38:43+08:00 WARN [conn 2068] error running query {connectTime=2023-06-27T10:37:34+08:00, connectionDb=gos_config_1021, error=table with same name 'BattleAction' added in 2 commits can't be merged, query=call dolt_merge('temp_dev-f1', 'temp_DEV')}

**Comment by lmy1218** [comment] 2023-06-27 02:42
I would like to know how to investigate and resolve such errors.

**Comment by max-hoffman** [comment] 2023-06-27 02:51
@fulghum is more of the expert on this and can comment more thoroughly tomorrow, but we currently can only merge two tables if either 1) they have a common ancestor commit, or 2) their schemas are identical. It is possible our check for (2) is faulty, and that would be a bug. It is also possible that we could improve cases where one table's schema is a subset of the other, for example identical in all ways except one has an extra index. But the "true" schema between two tables with no ancestor commit is ambiguous in the general case. Schema equality includes columns and types, primary key, indexes, index key ordering, collation, and check constraints.

**Comment by lmy1218** [comment] 2023-06-27 02:58
Thank you very much. I feel helpless with such issues because there are many new tables added during the merge. I've tried deleting the tables that cause errors, then recreating them after the merge and merging again to solve the problem.

**Comment by max-hoffman** [comment] 2023-06-27 03:08
One thing in [this issue](https://github.com/dolthub/dolt/issues/2145) that has not been implemented yet might help: a `dolt_patch('--schema')` function that generates a set of alter statements translating from one schema to another. It currently requires a common ancestor, but I think we could loosen that constraint specifically for schema A -> schema B.

**Comment by lmy1218** [comment] 2023-06-27 03:10
I found that there is no problem when merging these tables individually, but errors occur when they are combined with other new tables. Before merging, I checked that the structure of the two tables is consistent.
mysql> DESCRIBE BattleAction as of 'temp_DEV';
+---------------------+--------------+------+-----+---------+-------+
| Field               | Type         | Null | Key | Default | Extra |
+---------------------+--------------+------+-----+---------+-------+
| id                  | bigint       | NO   | PRI | NULL    |       |
| BattleAction_ek2ba7 | varchar(900) | YES  |     | NULL    |       |
| BattleAction_lqmzos | varchar(900) | YES  |     | NULL    |       |
| BattleAction_629oz1 | varchar(900) | YES  |     | NULL    |       |
| BattleAction_xr2ort | varchar(900) | YES  |     | NULL    |       |
| BattleAction_mlzwlv | varchar(900) | YES  |     | NULL    |       |
+---------------------+--------------+------+-----+---------+-------+
6 rows in set (0.01 sec)

mysql> DESCRIBE BattleAction as of 'temp_dev-f1';
+---------------------+--------------+------+-----+---------+-------+
| Field               | Type         | Null | Key | Default | Extra |
+---------------------+--------------+------+-----+---------+-------+
| id                  | bigint       | NO   | PRI | NULL    |       |
| BattleAction_ek2ba7 | varchar(900) | YES  |     | NULL    |       |
| BattleAction_lqmzos | varchar(900) | YES  |     | NULL    |       |
| BattleAction_629oz1 | varchar(900) | YES  |     | NULL    |       |
| BattleAction_xr2ort | varchar(900) | YES  |     | NULL    |       |
| BattleAction_mlzwlv | varchar(900) | YES  |     | NULL    |       |
+---------------------+--------------+------+-----+---------+-------+
6 rows in set (0.01 sec)


2023-06-27T10:51:33+08:00 WARN [conn 2094] error running query {connectTime=2023-06-27T10:50:39+08:00, connectionDb=gos_config_1021, error=table with same name 'BattleAction' added in 2 commits can't be merged, query=call dolt_merge('temp_dev-f1', 'temp_DEV')}

**Comment by max-hoffman** [comment] 2023-06-27 03:13
You'll want to use `show create table BattleAction`, note the other inputs to schema equality above.

**Comment by lmy1218** [comment] 2023-06-27 03:16
I tried that, and the result is the same.

mysql> show create table BattleAction as of 'temp_DEV';
+--------------+------------------------------------------------------------------+
| Table        | Create Table                                                     |
+--------------+------------------------------------------------------------------+
| BattleAction | CREATE TABLE `BattleAction` (                                    |
|              |   `id` bigint NOT NULL,                                          |
|              |   `BattleAction_ek2ba7` varchar(900),                            |
|              |   `BattleAction_lqmzos` varchar(900),                            |
|              |   `BattleAction_629oz1` varchar(900),                            |
|              |   `BattleAction_xr2ort` varchar(900),                            |
|              |   `BattleAction_mlzwlv` varchar(900),                            |
|              |   PRIMARY KEY (`id`)                                             |
|              | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+--------------+------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> show create table BattleAction as of 'temp_dev-f1';
+--------------+------------------------------------------------------------------+
| Table        | Create Table                                                     |
+--------------+------------------------------------------------------------------+
| BattleAction | CREATE TABLE `BattleAction` (                                    |
|              |   `id` bigint NOT NULL,                                          |
|              |   `BattleAction_ek2ba7` varchar(900),                            |
|              |   `BattleAction_lqmzos` varchar(900),                            |
|              |   `BattleAction_629oz1` varchar(900),                            |
|              |   `BattleAction_xr2ort` varchar(900),                            |
|              |   `BattleAction_mlzwlv` varchar(900),                            |
|              |   PRIMARY KEY (`id`)                                             |
|              | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin |
+--------------+------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by max-hoffman** [comment] 2023-06-27 03:22
Are there any foreign keys in other tables that reference BattleAction? This isn't really my specialty but there are cases where we silently generate background indexes to satisfy referential constraints.

If you are comfortable sending our team a zipfile of one of the databases that errors on merge, we could investigate on our side later this week. Can message us on discord if you want to keep the data private.

**Comment by lmy1218** [comment] 2023-06-27 03:27
Alright, I'll send it to your email later.

**Comment by lmy1218** [comment] 2023-06-27 03:39
I would like to know the method to create a compressed database file. I only found the command to export SQL in the documentation.

**Comment by lmy1218** [comment] 2023-06-27 06:12
[gos_config_1044.zip](https://github.com/dolthub/dolt/files/11878232/gos_config_1044.zip)
This is the backup file of the entire database, in which I want to merge the 'temp_dev-f1' branch into the 'temp_DEV' branch.

**Comment by lmy1218** [comment] 2023-06-27 09:01
I found that this error occurs sporadically.

**Comment by max-hoffman** [comment] 2023-06-27 17:00
There are some problems with the file you shared, which are maybe a result of different Dolt bugs. How did you create the zip?

The easiest way to share might just be taring the directory: `tar -zcvf database.tar.gz database/`

**Comment by lmy1218** [comment] 2023-06-28 01:57
[gos_config_1049.zip](https://github.com/dolthub/dolt/files/11888860/gos_config_1049.zip)
I apologize for the confusion, I thought it involved using the backup command. The file I attached is a compressed file directly from my database directory.

**Comment by max-hoffman** [comment] 2023-06-28 02:29
No worries, it's possible this is a Dolt problem. The backup command should be a valid way to share a database. It's just that both of these appear to be missing some things. The first zip file had all of the table data, but the `manifest` that tracks table states appears to be incomplete. And then the second one doesn't seem to have table data at all.

If you explain how you are generating these we might be able to help debug. Adding a DoltHub remote and pushing the database to DoltHub might be another option that gives you more salient feedback.

**Comment by lmy1218** [comment] 2023-06-28 02:47
[gos_config_1049.tar.gz](https://github.com/dolthub/dolt/files/11889189/gos_config_1049.tar.gz)
I generated it through the command you gave me, and executed this in the database directory: tar -zcvf gos_config_1049.tar.gz gos_config_1049.

**Comment by max-hoffman** [comment] 2023-06-28 02:54
I might be overlooking something, but this looks like an empty database from my end:
```
gos_config3> du -sh .dolt/noms/*
  0B	.dolt/noms/journal.idx
  0B	.dolt/noms/LOCK
4.0K	.dolt/noms/manifest
  0B	.dolt/noms/oldgen
1.0M	.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
```

The original one you sent me was 300KB and has tables that I can inspect manually, but the manifest appears to be corrupted which makes it a bit invisible to the SQL engine.
```
gos_config> du -sh .dolt/noms/*
300K	.dolt/noms/grjpq5ecr21121pjd228eh7mqmpv5grd
  0B	.dolt/noms/journal.idx
  0B	.dolt/noms/LOCK
4.0K	.dolt/noms/manifest
  0B	.dolt/noms/oldgen
1.0M	.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
```

```sql
gos_config> show tables;
Empty set (0.00 sec)
```

What do you see on your end before trying to package and send? Sharing the contents of `.dolt/noms/manifest` for the first zip file would also be useful if yours is in a queryable form.

**Comment by lmy1218** [comment] 2023-06-28 03:27
➜  gos_config_1049 du -sh .dolt/noms/*
  0B	.dolt/noms/LOCK
  0B	.dolt/noms/journal.idx
4.0K	.dolt/noms/manifest
  0B	.dolt/noms/oldgen
1.0M	.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
➜  gos_config_1049 dolt sql -q "show tables as of 'dev-f1'";
+---------------------------+
| Tables_in_gos_config_1049 |
+---------------------------+
| AssetType                 |
| BattleAction              |
| BattleActionType          |
| BattleAttrType            |
| BattleBuff                |
| BattleBuffClass           |
| BattleBuffRelation        |
| BattleBuffRelationType    |
| BattleBuffSubType         |
| BattleBuffType            |
| BattleDamageType          |
| BattleEventType           |
| BattleExpressionType      |
| BattleRelation            |
| BattleSkill               |
| BattleSoldier             |
| BattleSubBuff             |
| BattleTargetType          |
| BattleTroop               |
| Building                  |
| BuildingLevel             |
| BuildingType              |
| Buttons                   |
| CityGather                |
| CityGatherUnit            |
| ConstCommon               |
| CounterType               |
| ErrCode                   |
| I18nCN                    |
| I18nDE                    |
| I18nEN                    |
| I18nES                    |
| I18nFR                    |
| I18nVI                    |
| IdOpType                  |
| Item                      |
| ItemBagTag                |
| ItemEffectType            |
| ItemQulity                |
| ItemUseType               |
| MapType                   |
| Recover                   |
| RequirementType           |
| Research                  |
| ResearchCategory          |
| Rss                       |
| SoldierType               |
| Tip                       |
| TrendEndTriggerType       |
| TrendEndType              |
| TrendFinType              |
| TrendScopeType            |
| TrendShowTraceType        |
| TrendShowType             |
| WorldTrend                |
+---------------------------+

➜  ~ tar -zcvf gos_config_1049.tar.gz gos_config_1049/
a gos_config_1049
a gos_config_1049/.dolt
a gos_config_1049/.dolt/config.json
a gos_config_1049/.dolt/noms
a gos_config_1049/.dolt/temptf
a gos_config_1049/.dolt/repo_state.json
a gos_config_1049/.dolt/sql-server.lock
a gos_config_1049/.dolt/noms/oldgen
a gos_config_1049/.dolt/noms/manifest
a gos_config_1049/.dolt/noms/LOCK
a gos_config_1049/.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
a gos_config_1049/.dolt/noms/journal.idx


[gos_config_1049.tar.gz](https://github.com/dolthub/dolt/files/11889456/gos_config_1049.tar.gz)

**Comment by max-hoffman** [comment] 2023-06-28 04:10
Thanks for the pointer, the `main` branch being empty threw me off. This is what I get on branch 'temp_DEV' merging into 'temp_dev-f1':
```sql
gos_config3> call dolt_merge('temp_dev-f1');
Cannot create column Research_gomq1t, the tag 11397 was already used in table TrendEndType
```

It seems like there is a column identifier (tag) collision here.

This isn't exactly your error, but it's a similar schema inconsistency. Basically you want merge to do schema comparison in a slightly different way for two tables of the same name with no common ancestor. For two commits with no ancestor, maybe we disregard column identifiers altogether.

Are there any other commands erroring for this dataset that we should look at while we are at it?

**Comment by lmy1218** [comment] 2023-06-28 04:15
I would like to merge temp_dev-f1 into temp_DEV.

**Comment by lmy1218** [comment] 2023-06-28 04:17
mysql> use gos_config_1049;
Query OK (0.00 sec)
mysql> call dolt_checkout('temp_DEV');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.01 sec)

mysql> call dolt_merge('temp_dev-f1');
Error 1105: table with same name 'BattleAction' added in 2 commits can't be merged
mysql>

**Comment by max-hoffman** [comment] 2023-06-28 04:24
Ok I don't know exactly what is going on, but we will investigate this tomorrow and get back to you. Thanks for helping me get the dataset and setup.
```sql
gos_config_1049> use gos_config_1049;
Database changed
gos_config_1049> call dolt_checkout('temp_DEV');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)

gos_config_1049> call dolt_merge('temp_dev-f1');
could not map primary key column invalid
```

**Comment by lmy1218** [comment] 2023-06-28 04:27
Thank you very much for your help.

**Comment by max-hoffman** [comment] 2023-06-28 04:32
I think the last error I hit is also tag collisions. Primary keys are compared for equality by an identifier tag, other columns are compared by column name.

> // A primary key column in |inSch| is mapped to |outSch| if they share the same
// tag. A non-primary key column in |inSch| is mapped to |outSch| purely based on
// the name.

Someone will pick this up to fix in the morning US west coast time.

**Comment by lmy1218** [comment] 2023-06-28 06:27
My first issue has surfaced again. This error message is unrelated to the query SQL. 'AttrAdd' is a value of another table.


2023-06-28T06:25:41Z WARN [conn 3] error running query {connectTime=2023-06-28T06:25:40Z, connectionDb=gos_1041, error=error: 'AttrAdd' is not a valid value for 'bigint', query=SELECT DISTINCT gos_config_1041.BattleSkill.`BattleSkill_5b5mrz`, gos_config_1041.BattleSkill.`BattleSkill_kqtmbn`, gos_config_1041.BattleSkill.`BattleSkill_kz1lxu`, gos_config_1041.BattleSkill.`BattleSkill_mgyiml`, gos_config_1041.BattleSkill.`BattleSkill_n46my9`, gos_config_1041.BattleSkill.`BattleSkill_p89jpj`, gos_config_1041.BattleSkill.`BattleSkill_qdc5wm`, gos_config_1041.BattleSkill.`BattleSkill_rtlokc`, gos_config_1041.BattleSkill.`BattleSkill_ttmq4j`, gos_config_1041.BattleSkill.`BattleSkill_uul0h1`, gos_config_1041.BattleSkill.`BattleSkill_with2y`, gos_config_1041.BattleSkill.`BattleSkill_x2rkhz`, gos_config_1041.BattleSkill.`id`, gos_1041.gos_config_system.created_by as createdBy, gos_1041.gos_config_system.created_time as createdTime, gos_1041.gos_config_system.updated_by as updatedBy, gos_1041.gos_config_system.updated_time as updatedTime FROM gos_config_1041.BattleSkill as of 'dev-f1' LEFT OUTER JOIN gos_1041.gos_config_system ON gos_1041.gos_config_system.config_id = gos_config_1041.BattleSkill.id WHERE ( gos_1041.gos_config_system.branch_id = '4' AND gos_1041.gos_config_system.table_id = '1012') limit 0, 30}

**Comment by lmy1218** [comment] 2023-06-28 07:02
It might be an issue with the table joins, but the strange thing is that the error reported is data from another table, which makes it hard for me to solve.

mysql> select * from BattleSkill as of 'dev-f1';
+----+--------------------+--------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
| id | BattleSkill_ffjp9q | BattleSkill_gzvvfp       | BattleSkill_1z97fz | BattleSkill_3v1rlo | BattleSkill_vapwqm | BattleSkill_t4c3pj | BattleSkill_0f4yaz | BattleSkill_fvjnje | BattleSkill_hamk9h | BattleSkill_0pumyr | BattleSkill_2h253h | BattleSkill_u7z0ti |
+----+--------------------+--------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
| 1  | 0                  | EliminateCastActiveSkill | Self               | NULL               | NULL               | [1,2,3]            | NULL               | NULL               | NULL               | 1511000036         | NULL               | NULL               |
| 2  | 0                  | Eliminate                | Self               | NULL               | NULL               | [4]                | NULL               | NULL               | NULL               | 1511000036         | NULL               | NULL               |
| 3  | 2                  | Eliminate                | Self               | NULL               | NULL               | [5]                | NULL               | NULL               | NULL               | 1511000036         | NULL               | NULL               |
+----+--------------------+--------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT gos_config_2001.BattleSkill.`BattleSkill_0f4yaz`, gos_config_2001.BattleSkill.`BattleSkill_0pumyr`, gos_config_2001.BattleSkill.`BattleSkill_1z97fz`, gos_config_2001.BattleSkill.`BattleSkill_2h253h`, gos_config_2001.BattleSkill.`BattleSkill_3v1rlo`, gos_config_2001.BattleSkill.`BattleSkill_ffjp9q`, gos_config_2001.BattleSkill.`BattleSkill_fvjnje`, gos_config_2001.BattleSkill.`BattleSkill_gzvvfp`, gos_config_2001.BattleSkill.`BattleSkill_hamk9h`, gos_config_2001.BattleSkill.`BattleSkill_t4c3pj`, gos_config_2001.BattleSkill.`BattleSkill_u7z0ti`, gos_config_2001.BattleSkill.`BattleSkill_vapwqm`, gos_config_2001.BattleSkill.`id`, gos_2001.gos_config_system.created_by as createdBy, gos_2001.gos_config_system.created_time as createdTime, gos_2001.gos_config_system.updated_by as updatedBy, gos_2001.gos_config_system.updated_time as updatedTime FROM gos_config_2001.BattleSkill as of 'dev-f1' LEFT OUTER JOIN gos_2001.gos_config_system ON gos_2001.gos_config_system.config_id = gos_config_2001.BattleSkill.id WHERE ( gos_2001.gos_config_system.branch_id = '4' AND gos_2001.gos_config_system.table_id = '1039') limit 0, 30;
Error 1366: error: 'AttrAdd' is not a valid value for 'bigint'
mysql> select * from BattleBuff as of 'dev-f1';
+------------------+-------------------+-------------------+-------------------+
| id               | BattleBuff_5femsz | BattleBuff_6jchgz | BattleBuff_gwkyhm |
+------------------+-------------------+-------------------+-------------------+
| AttrAdd          | 属性增加buff      | true              | Attr              |
| BlessAll         | 大祝福            | true              | State             |
| BlessSelf        | 小祝福            | true              | State             |
| Block            | 格挡              | true              | State             |
| BlockCounter     | 格挡时可反击      | true              | State             |
| Burn             | 燃烧              | false             | Dot               |
| Dizzy            | 眩晕              | false             | State             |
| ForbidRecover    | 禁疗              | false             | State             |
| HpLastRecover    | 持续性回血        | true              | Hot               |
| HpTriggerRecover | 触发回血          | true              | State             |
+------------------+-------------------+-------------------+-------------------+
10 rows in set (0.00 sec)

mysql>

**Comment by max-hoffman** [comment] 2023-06-28 15:10
I agree that the join is confusing. My guess is that column identifier conflicts are causing us to think BattleBuff is BattleSkill at a prior commit because the primary keys accidentally have the same tag, maybe as the result of a bad merge. So the join error is a downstream effect of one of the merges from before completing but in a broken state.  If you can provide the state of the database that errors for the join query that would us repro, fix and test. Hopefully the root cause is similar for both issues and we could fix both at the same time. The way you are using Dolt is pretty new for us, we appreciate you taking the time to help us document, test and fix this usage pattern.

**Comment by max-hoffman** [comment] 2023-06-29 02:57
We have some extra comments after looking at this today.

If possible, we would recommend basing all of your branches on a common schema branch. The common branch would have tables, desired schemas, but no data. The workflow for making a new branch would be something like `call dolt_checkout('new-branch', 'schema-branch')`. Renaming tables and columns for specific branches, and merging between branches will be much safer this way at the moment.

In your current workflow, all our your branches have no "common ancestor" to trace table and column lineage. The way we currently track lineage is by embedding "tags" to identify columns, but the way they are generated is dependent on the order tables are made. Here is one example where we see different tags for the same table between two branches:

```sql
max-hoffman@Maxs-MBP ~/D/d/d/gos_config_1044> dolt schema tags Buttons;
+---------+----------------+-------+
| table   | column         | tag   |
+---------+----------------+-------+
| Buttons | id             | 11550 |
| Buttons | Buttons_4q21zr | 935   |
| Buttons | Buttons_0ozo6q | 788   |
| Buttons | Buttons_aovv68 | 9160  |
+---------+----------------+-------+

max-hoffman@Maxs-MBP ~/D/d/d/gos_config_1044> dolt checkout temp_dev-f1;
Switched to branch 'temp_dev-f1'
max-hoffman@Maxs-MBP ~/D/d/d/gos_config_1044> dolt schema tags Buttons;
+---------+----------------+-------+
| table   | column         | tag   |
+---------+----------------+-------+
| Buttons | id             | 11550 |
| Buttons | Buttons_4q21zr | 12175 |
| Buttons | Buttons_0ozo6q | 788   |
| Buttons | Buttons_aovv68 | 4928  |
+---------+----------------+-------+
```

And then a tag conflict error merging them:
```
Cannot create column Buttons_4q21zr, the tag 12175 was already used in table TrendShowType
```

In extreme cases, it is possible to have the opposite problem. Two tables A and B on different branches might accidentally have the same primary key tag, in which case a merge is going to try to reconcile and merge their schemas.

We do this is to more easily track column renames and schema changes through a database's commit history, which so far is a much more common merge pattern.

We don't all of the errors your are seeing, but you are generating enough tables and branches that you might be hitting several of these tag collision edge cases.

We are still interested in the data to reproduce your join error. And we would be interested in following up to make this work better out of the box. Let us know if the common schema branch is not a satisfactory workaround.

**Comment by lmy1218** [comment] 2023-06-29 03:19
I apologize, but what I'm currently doing involves different branches potentially having different table structures. Since Dolt does not support table structure merging, I have implemented this myself by creating it in another branch then merging it. So, it's almost impossible to make them have the same common branch.

**Comment by max-hoffman** [comment] 2023-06-29 03:29
Any chance you could give an overview of what you are trying to do? What do the different branches mean, where there is structure and data overlap, where you expect table, schema, column, data differences? That might make it easier for us to understand your goals better.

We are working through how to optimally detect the overlap between disparate branches with no common ancestor, but there are a lot of tradeoffs. Name-based matching behaves poorly through table and column renames. It is possible to support multiple strategies that users can switch between. We can do things like manually assign column tags to force certain tables to merge cleanly. We would like to help figure out a short-term workaround if possible.

**Comment by lmy1218** [comment] 2023-06-29 03:41
What I'm doing right now is, the dev branch has tables A, B, and C, while the prod branch has tables A and B. I hope that when merging from dev to prod, it could also merge the C table into prod. Then I found that Dolt does not support table merge, so I manually copied the C table into prod, and then initiated the merge from dev to prod.

**Comment by max-hoffman** [comment] 2023-06-29 03:57
So we should support table merge in most cases...If you branch dev off of prod, and then add C to dev, the dev schema will merge back cleanly into prod. If you have 3 dev branches and all of them make C with different schemas, then you would need to reconcile those schemas before merging with one-another, but you would still be in a better with them all having a common ancestor.

**Comment by lmy1218** [comment] 2023-06-29 06:51
Alright, I understand what you mean now. Dolt can indeed help me merge table additions and deletions. Thank you very much. However, the issue of unrelated errors being reported during another table's associated query remains unresolved, and this error has nothing to do with branch merging, as I've never initiated a merge.

**Comment by max-hoffman** [comment] 2023-06-29 14:21
The first place I would still look for that error is tag collisions. If the `BattleBuff.id` tag collides with a column in  `gos_config_1041.BattleSkill as of 'dev-f1'` or `gos_1041.gos_config_system.config_id`. I don't have enough to reproduce the error yet. The table tags for the branch states you are joining might be enough, a database that lets one of us to repro locally definitely lets us fix it. If you are worried about the data being private we can make a private DoltHub remote or a google drive link or something.

**Comment by timsehn** [comment] 2023-08-25 21:46
We've made a ton of progress on schema merges since this was filed. I'm going to close this. If you are still having issues with schema merge please open a new issue with a newer repro.

**Closed by timsehn** 2023-08-25 21:46 UTC
Labels: bug, sql, analyzer, customer issue
